// ============================================================
// PHASE 3 word banks — A2+ (weeks 23-30).
//
// Phase 2 separated the topics; Phase 3 keeps that separation and adds
// intent. The department now has to *persuade*, *explain a rule*,
// *commit to a time*, *route work to another team*, *absorb a complaint*
// and *hand over a shift* — so the banks are organised by speech act,
// not by object.
//
// Each slot carries a REQUIRED PART OF SPEECH, because the spine drops
// these words into fixed frames. See docs/phase3-bank-contract.md:
//   noun-phrase slots  — must read correctly after "the "
//   verb-phrase slots  — bare infinitive, must read after "I will " / "I can "
// Getting this wrong is what produced the fragment defects that
// scripts/qa-full.ts caught in Phase 2.
//
// 8 slots × 12 words = 96 department-specific headwords each.
//
// Enforced by scripts/verify-content.ts:
//  · No word may repeat a headword the department already met in
//    Phase 0, 1 or 2 (intra-department duplication gate).
//  · >=65% of each week's headwords must be department-specific.
//  · Sentences built from these words stay within the 16-word A2+ cap.
// ============================================================

export type P3Word = { word: string; phonetic: string; definition: string; icon: string };

export type P3Bank = {
  /** W23 — noun phrases. What this department can suggest as an upgrade. */
  upgrades: P3Word[];
  /** W24 — noun phrases naming a fee, charge or rule it must explain. */
  policies: P3Word[];
  /** W25 — BARE VERB PHRASES. What it promises to do, and by when. */
  commitments: P3Word[];
  /** W26 — noun phrases naming the teams and roles it routes work to. */
  partners: P3Word[];
  /** W27 — noun phrases naming the complaints it routinely absorbs. */
  complaints: P3Word[];
  /** W28 — BARE VERB PHRASES. The remedies it can conditionally offer. */
  solutions: P3Word[];
  /** W29 — noun phrases naming what appears in its shift handover. */
  handover: P3Word[];
  /** W30 — noun phrases, mixed, for the checkpoint week. */
  wrapUp: P3Word[];
};

const FO_BANK: P3Bank = {
  upgrades: [
    { word: "Sea-view room", phonetic: "/siː vjuː ruːm/", definition: "Phòng nhìn ra biển", icon: "🌊" },
    { word: "Executive suite", phonetic: "/ɪɡˈzekjətɪv swiːt/", definition: "Phòng hạng thương gia", icon: "🥂" },
    { word: "Deluxe room", phonetic: "/dəˈlʌks ruːm/", definition: "Phòng cao cấp rộng hơn", icon: "✨" },
    { word: "Junior suite", phonetic: "/ˈdʒuːniə swiːt/", definition: "Phòng rộng có góc tiếp khách", icon: "🛋️" },
    { word: "Club floor room", phonetic: "/klʌb flɔː ruːm/", definition: "Phòng ở tầng có phòng chờ riêng", icon: "🎩" },
    { word: "Family room", phonetic: "/ˈfæməli ruːm/", definition: "Phòng dành cho gia đình", icon: "👪" },
    { word: "Poolside room", phonetic: "/ˈpuːlsaɪd ruːm/", definition: "Phòng cạnh hồ bơi", icon: "🏊" },
    { word: "Top-floor room", phonetic: "/tɒp flɔː ruːm/", definition: "Phòng ở tầng trên cùng", icon: "🏙️" },
    { word: "Balcony room", phonetic: "/ˈbælkəni ruːm/", definition: "Phòng có ban công", icon: "🪴" },
    { word: "Accessible room", phonetic: "/əkˈsesəbl ruːm/", definition: "Phòng dành cho người khuyết tật", icon: "♿" },
    { word: "Garden-view room", phonetic: "/ˈɡɑːdn vjuː ruːm/", definition: "Phòng nhìn ra vườn", icon: "🌳" },
    { word: "Penthouse suite", phonetic: "/ˈpenthaʊs swiːt/", definition: "Phòng sang trọng trên đỉnh tòa nhà", icon: "👑" },
  ],
  policies: [
    { word: "Late check-out fee", phonetic: "/leɪt tʃek aʊt fiː/", definition: "Phí trả phòng trễ giờ", icon: "⏰" },
    { word: "Cancellation fee", phonetic: "/ˌkænsəˈleɪʃn fiː/", definition: "Phí hủy đặt phòng", icon: "❌" },
    { word: "No-show charge", phonetic: "/nəʊ ʃəʊ tʃɑːdʒ/", definition: "Phí khách đặt phòng nhưng không đến", icon: "🚫" },
    { word: "Rollaway bed fee", phonetic: "/ˈrəʊləweɪ bed fiː/", definition: "Phí giường phụ di động", icon: "🛏️" },
    { word: "Minibar charge", phonetic: "/ˈmɪnibɑː tʃɑːdʒ/", definition: "Tiền đồ uống trong tủ lạnh phòng", icon: "🥤" },
    { word: "City tax", phonetic: "/ˈsɪti tæks/", definition: "Thuế thành phố thu theo đêm", icon: "🏛️" },
    { word: "Room-change fee", phonetic: "/ruːm tʃeɪndʒ fiː/", definition: "Phí đổi sang phòng khác", icon: "🔄" },
    { word: "Damage charge", phonetic: "/ˈdæmɪdʒ tʃɑːdʒ/", definition: "Tiền bồi thường hư hỏng", icon: "💥" },
    { word: "Key replacement fee", phonetic: "/kiː rɪˈpleɪsmənt fiː/", definition: "Phí làm lại thẻ mở cửa", icon: "🔑" },
    { word: "Pet fee", phonetic: "/pet fiː/", definition: "Phí mang theo thú cưng", icon: "🐕" },
    { word: "No-smoking penalty", phonetic: "/nəʊ ˈsməʊkɪŋ ˈpenəlti/", definition: "Tiền phạt hút thuốc trong phòng", icon: "🚭" },
    { word: "Guest registration rule", phonetic: "/ɡest ˌredʒɪˈstreɪʃn ruːl/", definition: "Quy định khai báo lưu trú", icon: "📋" },
  ],
  commitments: [
    { word: "Prepare your room", phonetic: "/prɪˈpeə jɔː ruːm/", definition: "Chuẩn bị phòng cho quý khách", icon: "🧹" },
    { word: "Check with housekeeping", phonetic: "/tʃek wɪð ˈhaʊskiːpɪŋ/", definition: "Hỏi lại bộ phận buồng phòng", icon: "🧺" },
    { word: "Print your invoice", phonetic: "/prɪnt jɔː ˈɪnvɔɪs/", definition: "In hóa đơn cho khách", icon: "🧾" },
    { word: "Send a bellman up", phonetic: "/send ə ˈbelmən ʌp/", definition: "Cho nhân viên hành lý lên phòng", icon: "🛎️" },
    { word: "Update your booking", phonetic: "/ˈʌpdeɪt jɔː ˈbʊkɪŋ/", definition: "Cập nhật lại đặt phòng", icon: "💻" },
    { word: "Hold your luggage", phonetic: "/həʊld jɔː ˈlʌɡɪdʒ/", definition: "Giữ hành lý giúp khách", icon: "🧳" },
    { word: "Confirm your late check-out", phonetic: "/kənˈfɜːm jɔː leɪt tʃek aʊt/", definition: "Xác nhận việc trả phòng trễ", icon: "⏰" },
    { word: "Book your airport transfer", phonetic: "/bʊk jɔː ˈeəpɔːt ˈtrænsfɜː/", definition: "Đặt xe đưa đón sân bay", icon: "🚐" },
    { word: "Arrange a taxi", phonetic: "/əˈreɪndʒ ə ˈtæksi/", definition: "Gọi xe cho khách", icon: "🚕" },
    { word: "Check the room status", phonetic: "/tʃek ðə ruːm ˈsteɪtəs/", definition: "Kiểm tra tình trạng phòng", icon: "🔎" },
    { word: "Deliver your message", phonetic: "/dɪˈlɪvə jɔː ˈmesɪdʒ/", definition: "Chuyển lời nhắn giúp khách", icon: "✉️" },
    { word: "Reprogram your key card", phonetic: "/ˌriːˈprəʊɡræm jɔː kiː kɑːd/", definition: "Làm lại thẻ mở cửa phòng", icon: "🔑" },
  ],
  partners: [
    { word: "Housekeeping team", phonetic: "/ˈhaʊskiːpɪŋ tiːm/", definition: "Bộ phận buồng phòng", icon: "🧺" },
    { word: "Bell desk", phonetic: "/bel desk/", definition: "Quầy hành lý", icon: "🛎️" },
    { word: "Engineering team", phonetic: "/ˌendʒɪˈnɪərɪŋ tiːm/", definition: "Bộ phận kỹ thuật", icon: "🔧" },
    { word: "Reservations team", phonetic: "/ˌrezəˈveɪʃnz tiːm/", definition: "Bộ phận đặt phòng", icon: "📅" },
    { word: "Night manager", phonetic: "/naɪt ˈmænɪdʒə/", definition: "Quản lý ca đêm", icon: "🌙" },
    { word: "Room attendant", phonetic: "/ruːm əˈtendənt/", definition: "Nhân viên dọn phòng", icon: "🧹" },
    { word: "Guest relations officer", phonetic: "/ɡest rɪˈleɪʃnz ˈɒfɪsə/", definition: "Nhân viên chăm sóc khách", icon: "🤝" },
    { word: "Security officer", phonetic: "/sɪˈkjʊərəti ˈɒfɪsə/", definition: "Nhân viên an ninh", icon: "🛡️" },
    { word: "Airport driver", phonetic: "/ˈeəpɔːt ˈdraɪvə/", definition: "Tài xế đón khách sân bay", icon: "🚐" },
    { word: "Night auditor", phonetic: "/naɪt ˈɔːdɪtə/", definition: "Nhân viên kiểm toán đêm", icon: "📊" },
    { word: "Floor supervisor", phonetic: "/flɔː ˈsuːpəvaɪzə/", definition: "Giám sát tầng phòng", icon: "🏢" },
    { word: "Valet parking attendant", phonetic: "/ˈvæleɪ ˈpɑːkɪŋ əˈtendənt/", definition: "Nhân viên đỗ xe hộ khách", icon: "🅿️" },
  ],
  complaints: [
    { word: "Room delay", phonetic: "/ruːm dɪˈleɪ/", definition: "Việc phòng chưa sẵn sàng", icon: "⏳" },
    { word: "Noisy corridor", phonetic: "/ˈnɔɪzi ˈkɒrɪdɔː/", definition: "Hành lang ồn ào", icon: "🔊" },
    { word: "Wrong room rate", phonetic: "/rɒŋ ruːm reɪt/", definition: "Giá phòng bị tính sai", icon: "💸" },
    { word: "Double charge", phonetic: "/ˈdʌbl tʃɑːdʒ/", definition: "Bị thu tiền hai lần", icon: "💳" },
    { word: "Long check-in queue", phonetic: "/lɒŋ tʃek ɪn kjuː/", definition: "Hàng chờ nhận phòng quá dài", icon: "🧍" },
    { word: "Missing luggage", phonetic: "/ˈmɪsɪŋ ˈlʌɡɪdʒ/", definition: "Hành lý bị thất lạc", icon: "🧳" },
    { word: "Air-conditioning noise", phonetic: "/eə kənˈdɪʃənɪŋ nɔɪz/", definition: "Tiếng ồn từ máy lạnh", icon: "❄️" },
    { word: "Key card failure", phonetic: "/kiː kɑːd ˈfeɪljə/", definition: "Thẻ phòng không mở được cửa", icon: "🔑" },
    { word: "Dirty bathroom", phonetic: "/ˈdɜːti ˈbɑːθruːm/", definition: "Phòng tắm chưa được dọn sạch", icon: "🚿" },
    { word: "Wake-up call mistake", phonetic: "/ˈweɪk ʌp kɔːl mɪˈsteɪk/", definition: "Gọi báo thức sai giờ", icon: "⏰" },
    { word: "Weak wifi signal", phonetic: "/wiːk ˈwaɪfaɪ ˈsɪɡnl/", definition: "Sóng mạng không dây yếu", icon: "📶" },
    { word: "Overbooking mix-up", phonetic: "/ˌəʊvəˈbʊkɪŋ ˈmɪks ʌp/", definition: "Nhầm lẫn do nhận quá số phòng", icon: "📚" },
  ],
  solutions: [
    { word: "Move you to another room", phonetic: "/muːv juː tuː əˈnʌðə ruːm/", definition: "Chuyển khách sang phòng khác", icon: "🔄" },
    { word: "Waive the late fee", phonetic: "/weɪv ðə leɪt fiː/", definition: "Miễn phí trả phòng trễ", icon: "🆓" },
    { word: "Arrange late check-out", phonetic: "/əˈreɪndʒ leɪt tʃek aʊt/", definition: "Thu xếp cho khách trả phòng trễ", icon: "⏰" },
    { word: "Upgrade you free of charge", phonetic: "/ˈʌpɡreɪd juː friː əv tʃɑːdʒ/", definition: "Nâng hạng phòng miễn phí", icon: "⬆️" },
    { word: "Correct the room rate", phonetic: "/kəˈrekt ðə ruːm reɪt/", definition: "Sửa lại giá phòng cho đúng", icon: "💰" },
    { word: "Send engineering to the room", phonetic: "/send ˌendʒɪˈnɪərɪŋ tuː ðə ruːm/", definition: "Cho kỹ thuật lên phòng kiểm tra", icon: "🔧" },
    { word: "Store your bags downstairs", phonetic: "/stɔː jɔː bæɡz ˌdaʊnˈsteəz/", definition: "Giữ hành lý ở tầng dưới", icon: "🧳" },
    { word: "Offer a free breakfast", phonetic: "/ˈɒfə ə friː ˈbrekfəst/", definition: "Mời khách bữa sáng miễn phí", icon: "🥐" },
    { word: "Block a quieter room", phonetic: "/blɒk ə ˈkwaɪətə ruːm/", definition: "Giữ sẵn một phòng yên tĩnh hơn", icon: "🤫" },
    { word: "Remove the charge", phonetic: "/rɪˈmuːv ðə tʃɑːdʒ/", definition: "Bỏ khoản phí đó đi", icon: "➖" },
    { word: "Bring the key to you", phonetic: "/brɪŋ ðə kiː tuː juː/", definition: "Mang thẻ phòng đến cho khách", icon: "🔑" },
    { word: "Extend your stay one night", phonetic: "/ɪkˈstend jɔː steɪ wʌn naɪt/", definition: "Cho khách ở thêm một đêm", icon: "🌙" },
  ],
  handover: [
    { word: "Arrival list", phonetic: "/əˈraɪvl lɪst/", definition: "Danh sách khách sẽ đến", icon: "🛬" },
    { word: "Departure list", phonetic: "/dɪˈpɑːtʃə lɪst/", definition: "Danh sách khách sẽ trả phòng", icon: "🛫" },
    { word: "Room status report", phonetic: "/ruːm ˈsteɪtəs rɪˈpɔːt/", definition: "Báo cáo tình trạng các phòng", icon: "🗂️" },
    { word: "Pending request", phonetic: "/ˈpendɪŋ rɪˈkwest/", definition: "Yêu cầu còn chờ xử lý", icon: "⏳" },
    { word: "Special attention list", phonetic: "/ˈspeʃl əˈtenʃn lɪst/", definition: "Danh sách khách cần lưu ý", icon: "⭐" },
    { word: "Room discrepancy report", phonetic: "/ruːm dɪsˈkrepənsi rɪˈpɔːt/", definition: "Báo cáo phòng lệch tình trạng", icon: "🔍" },
    { word: "Occupancy figure", phonetic: "/ˈɒkjəpənsi ˈfɪɡə/", definition: "Số liệu công suất phòng", icon: "📊" },
    { word: "Cash float", phonetic: "/kæʃ fləʊt/", definition: "Tiền quỹ đầu ca", icon: "💵" },
    { word: "Key inventory", phonetic: "/kiː ˈɪnvəntri/", definition: "Số thẻ phòng còn trong quầy", icon: "🔑" },
    { word: "Wake-up call list", phonetic: "/ˈweɪk ʌp kɔːl lɪst/", definition: "Danh sách khách cần báo thức", icon: "⏰" },
    { word: "Group arrival note", phonetic: "/ɡruːp əˈraɪvl nəʊt/", definition: "Ghi chú đoàn khách sắp đến", icon: "👥" },
    { word: "Out-of-order room list", phonetic: "/aʊt əv ˈɔːdə ruːm lɪst/", definition: "Danh sách phòng đang hỏng", icon: "🚧" },
  ],
  wrapUp: [
    { word: "Room number", phonetic: "/ruːm ˈnʌmbə/", definition: "Số phòng của khách", icon: "🔢" },
    { word: "Rate per night", phonetic: "/reɪt pɜː naɪt/", definition: "Giá phòng mỗi đêm", icon: "💲" },
    { word: "Late check-out time", phonetic: "/leɪt tʃek aʊt taɪm/", definition: "Giờ trả phòng trễ đã thỏa thuận", icon: "🕐" },
    { word: "Pick-up time", phonetic: "/ˈpɪk ʌp taɪm/", definition: "Giờ xe đón khách", icon: "🚐" },
    { word: "Number of nights", phonetic: "/ˈnʌmbə əv naɪts/", definition: "Số đêm lưu trú", icon: "🌙" },
    { word: "Breakfast arrangement", phonetic: "/ˈbrekfəst əˈreɪndʒmənt/", definition: "Sắp xếp bữa sáng cho khách", icon: "🥐" },
    { word: "Payment method", phonetic: "/ˈpeɪmənt ˈmeθəd/", definition: "Hình thức thanh toán", icon: "💳" },
    { word: "Room preference", phonetic: "/ruːm ˈprefrəns/", definition: "Yêu cầu riêng về loại phòng", icon: "🛏️" },
    { word: "Luggage count", phonetic: "/ˈlʌɡɪdʒ kaʊnt/", definition: "Số kiện hành lý", icon: "🧳" },
    { word: "Final balance", phonetic: "/ˈfaɪnl ˈbæləns/", definition: "Số tiền còn phải trả", icon: "🧾" },
    { word: "Guest signature", phonetic: "/ɡest ˈsɪɡnətʃə/", definition: "Chữ ký của khách", icon: "✍️" },
    { word: "Flight time", phonetic: "/flaɪt taɪm/", definition: "Giờ bay của khách", icon: "✈️" },
  ],
};

const FB_BANK: P3Bank = {
  upgrades: [
    { word: "Tasting menu", phonetic: "/ˈteɪstɪŋ ˈmenjuː/", definition: "Thực đơn nếm thử nhiều món", icon: "🍽️" },
    { word: "Wine pairing", phonetic: "/waɪn ˈpeərɪŋ/", definition: "Rượu vang chọn kèm từng món", icon: "🍷" },
    { word: "Private dining room", phonetic: "/ˈpraɪvət ˈdaɪnɪŋ ruːm/", definition: "Phòng ăn riêng", icon: "🚪" },
    { word: "Chef's table", phonetic: "/ʃefs ˈteɪbl/", definition: "Bàn ăn ngay tại bếp", icon: "👨‍🍳" },
    { word: "Premium set menu", phonetic: "/ˈpriːmiəm set ˈmenjuː/", definition: "Suất ăn cố định cao cấp", icon: "⭐" },
    { word: "Sparkling wine", phonetic: "/ˈspɑːklɪŋ waɪn/", definition: "Rượu vang có ga", icon: "🥂" },
    { word: "Aged steak", phonetic: "/eɪdʒd steɪk/", definition: "Bò bít tết ủ lâu ngày", icon: "🥩" },
    { word: "Seafood platter", phonetic: "/ˈsiːfuːd ˈplætə/", definition: "Đĩa hải sản tổng hợp", icon: "🦞" },
    { word: "Cheese board", phonetic: "/tʃiːz bɔːd/", definition: "Đĩa phô mai", icon: "🧀" },
    { word: "Cocktail of the day", phonetic: "/ˈkɒkteɪl əv ðə deɪ/", definition: "Đồ uống pha chế trong ngày", icon: "🍸" },
    { word: "Sunset view table", phonetic: "/ˈsʌnset vjuː ˈteɪbl/", definition: "Bàn ngắm hoàng hôn", icon: "🌅" },
    { word: "Signature cocktail", phonetic: "/ˈsɪɡnətʃə ˈkɒkteɪl/", definition: "Đồ uống pha chế đặc trưng", icon: "🍹" },
  ],
  policies: [
    { word: "Corkage fee", phonetic: "/ˈkɔːkɪdʒ fiː/", definition: "Phí mở rượu khách tự mang", icon: "🍾" },
    { word: "Service charge", phonetic: "/ˈsɜːvɪs tʃɑːdʒ/", definition: "Phí phục vụ", icon: "💵" },
    { word: "Minimum spend", phonetic: "/ˈmɪnɪməm spend/", definition: "Mức chi tiêu tối thiểu", icon: "💳" },
    { word: "Cancellation fee", phonetic: "/ˌkænsəˈleɪʃn fiː/", definition: "Phí hủy đặt bàn", icon: "❌" },
    { word: "Cover charge", phonetic: "/ˈkʌvə tʃɑːdʒ/", definition: "Phí chỗ ngồi mỗi khách", icon: "🎟️" },
    { word: "Group deposit", phonetic: "/ɡruːp dɪˈpɒzɪt/", definition: "Tiền cọc cho đoàn khách", icon: "🏦" },
    { word: "Last order time", phonetic: "/lɑːst ˈɔːdə taɪm/", definition: "Giờ nhận gọi món cuối", icon: "🕙" },
    { word: "Table time limit", phonetic: "/ˈteɪbl taɪm ˈlɪmɪt/", definition: "Thời gian giữ bàn tối đa", icon: "⏱️" },
    { word: "Outside food rule", phonetic: "/ˌaʊtˈsaɪd fuːd ruːl/", definition: "Quy định không mang đồ ăn ngoài", icon: "🚫" },
    { word: "No-show charge", phonetic: "/ˈnəʊ ʃəʊ tʃɑːdʒ/", definition: "Phí đặt bàn nhưng không đến", icon: "📵" },
    { word: "Alcohol age rule", phonetic: "/ˈælkəhɒl eɪdʒ ruːl/", definition: "Quy định tuổi được uống rượu bia", icon: "🔞" },
    { word: "Late arrival rule", phonetic: "/leɪt əˈraɪvl ruːl/", definition: "Quy định khách đến muộn", icon: "🕘" },
  ],
  commitments: [
    { word: "Check with the kitchen", phonetic: "/tʃek wɪð ðə ˈkɪtʃɪn/", definition: "Hỏi lại bếp", icon: "🍳" },
    { word: "Serve your main course", phonetic: "/sɜːv jɔː meɪn kɔːs/", definition: "Phục vụ món chính của quý khách", icon: "🍛" },
    { word: "Bring your starter", phonetic: "/brɪŋ jɔː ˈstɑːtə/", definition: "Mang món khai vị ra", icon: "🥗" },
    { word: "Speed up your order", phonetic: "/spiːd ʌp jɔː ˈɔːdə/", definition: "Đẩy nhanh món khách gọi", icon: "⏩" },
    { word: "Chill the wine", phonetic: "/tʃɪl ðə waɪn/", definition: "Làm lạnh rượu vang", icon: "🍾" },
    { word: "Reset your table", phonetic: "/ˌriːˈset jɔː ˈteɪbl/", definition: "Bày lại bàn của khách", icon: "🪑" },
    { word: "Hold the dessert", phonetic: "/həʊld ðə dɪˈzɜːt/", definition: "Giữ món tráng miệng lại sau", icon: "🍰" },
    { word: "Send the order now", phonetic: "/send ði ˈɔːdə naʊ/", definition: "Chuyển phiếu gọi món ngay", icon: "📨" },
    { word: "Prepare a nut-free dish", phonetic: "/prɪˈpeər ə nʌt friː dɪʃ/", definition: "Làm món không có hạt", icon: "🥜" },
    { word: "Set up the private room", phonetic: "/set ʌp ðə ˈpraɪvət ruːm/", definition: "Chuẩn bị phòng ăn riêng", icon: "🚪" },
    { word: "Open a new bottle", phonetic: "/ˈəʊpən ə njuː ˈbɒtl/", definition: "Khai một chai mới", icon: "🍷" },
    { word: "Top up your water", phonetic: "/tɒp ʌp jɔː ˈwɔːtə/", definition: "Rót thêm nước cho khách", icon: "💧" },
  ],
  partners: [
    { word: "Head chef", phonetic: "/hed ʃef/", definition: "Bếp trưởng", icon: "👨‍🍳" },
    { word: "Sommelier", phonetic: "/səˈmeljeɪ/", definition: "Chuyên viên tư vấn rượu vang", icon: "🍷" },
    { word: "Pastry section", phonetic: "/ˈpeɪstri ˈsekʃn/", definition: "Bộ phận bánh ngọt", icon: "🍰" },
    { word: "Bar team", phonetic: "/bɑː tiːm/", definition: "Tổ pha chế", icon: "🍸" },
    { word: "Banquet team", phonetic: "/ˈbæŋkwɪt tiːm/", definition: "Tổ tiệc", icon: "🎉" },
    { word: "Stewarding team", phonetic: "/ˈstjuːədɪŋ tiːm/", definition: "Tổ rửa bát và vệ sinh bếp", icon: "🧼" },
    { word: "Restaurant manager", phonetic: "/ˈrestrɒnt ˈmænɪdʒə/", definition: "Quản lý nhà hàng", icon: "🧑‍💼" },
    { word: "Reservations team", phonetic: "/ˌrezəˈveɪʃnz tiːm/", definition: "Bộ phận nhận đặt bàn", icon: "📒" },
    { word: "Room service team", phonetic: "/ruːm ˈsɜːvɪs tiːm/", definition: "Tổ phục vụ tại phòng", icon: "🛎️" },
    { word: "Food runner", phonetic: "/fuːd ˈrʌnə/", definition: "Nhân viên chạy món", icon: "🏃" },
    { word: "Kitchen team", phonetic: "/ˈkɪtʃɪn tiːm/", definition: "Tổ bếp", icon: "🔪" },
    { word: "Bar manager", phonetic: "/bɑː ˈmænɪdʒə/", definition: "Quản lý quầy pha chế", icon: "🍹" },
  ],
  complaints: [
    { word: "Cold food", phonetic: "/kəʊld fuːd/", definition: "Đồ ăn bị nguội", icon: "🥶" },
    { word: "Slow service", phonetic: "/sləʊ ˈsɜːvɪs/", definition: "Phục vụ chậm", icon: "🐌" },
    { word: "Wrong order", phonetic: "/rɒŋ ˈɔːdə/", definition: "Mang nhầm món", icon: "❌" },
    { word: "Overcooked steak", phonetic: "/ˌəʊvəˈkʊkt steɪk/", definition: "Bò bít tết chín quá", icon: "🥩" },
    { word: "Missing dish", phonetic: "/ˈmɪsɪŋ dɪʃ/", definition: "Món bị thiếu", icon: "🔍" },
    { word: "Salty soup", phonetic: "/ˈsɔːlti suːp/", definition: "Món súp bị mặn", icon: "🧂" },
    { word: "Warm beer", phonetic: "/wɔːm bɪə/", definition: "Bia không đủ lạnh", icon: "🍺" },
    { word: "Dirty glass", phonetic: "/ˈdɜːti ɡlɑːs/", definition: "Ly bị bẩn", icon: "🥃" },
    { word: "Small portion", phonetic: "/smɔːl ˈpɔːʃn/", definition: "Khẩu phần quá ít", icon: "🍽️" },
    { word: "Billing mistake", phonetic: "/ˈbɪlɪŋ mɪˈsteɪk/", definition: "Tính tiền sai", icon: "🧾" },
    { word: "Lost reservation", phonetic: "/lɒst ˌrezəˈveɪʃn/", definition: "Mất thông tin đặt bàn", icon: "📕" },
    { word: "Noisy table", phonetic: "/ˈnɔɪzi ˈteɪbl/", definition: "Bàn bên cạnh quá ồn", icon: "🔊" },
  ],
  solutions: [
    { word: "Replace the dish", phonetic: "/rɪˈpleɪs ðə dɪʃ/", definition: "Đổi món khác cho khách", icon: "🔄" },
    { word: "Remove it from the bill", phonetic: "/rɪˈmuːv ɪt frəm ðə bɪl/", definition: "Bỏ món đó khỏi hóa đơn", icon: "✂️" },
    { word: "Bring a fresh one", phonetic: "/brɪŋ ə freʃ wʌn/", definition: "Mang phần mới ra", icon: "✨" },
    { word: "Offer a free dessert", phonetic: "/ˈɒfər ə friː dɪˈzɜːt/", definition: "Mời món tráng miệng miễn phí", icon: "🍰" },
    { word: "Move you to another table", phonetic: "/muːv juː tu əˈnʌðə ˈteɪbl/", definition: "Chuyển khách sang bàn khác", icon: "🪑" },
    { word: "Reheat your main course", phonetic: "/ˌriːˈhiːt jɔː meɪn kɔːs/", definition: "Hâm nóng lại món chính", icon: "🔥" },
    { word: "Cancel the order", phonetic: "/ˈkænsl ði ˈɔːdə/", definition: "Hủy món đã gọi", icon: "🚫" },
    { word: "Bring a different drink", phonetic: "/brɪŋ ə ˈdɪfrənt drɪŋk/", definition: "Mang đồ uống khác ra", icon: "🍹" },
    { word: "Take off the service charge", phonetic: "/teɪk ɒf ðə ˈsɜːvɪs tʃɑːdʒ/", definition: "Miễn phí phục vụ", icon: "💵" },
    { word: "Cook a new steak", phonetic: "/kʊk ə njuː steɪk/", definition: "Làm lại phần bò bít tết", icon: "🥩" },
    { word: "Wrap it to take away", phonetic: "/ræp ɪt tə teɪk əˈweɪ/", definition: "Gói mang về cho khách", icon: "🥡" },
    { word: "Ask my manager to come", phonetic: "/ɑːsk maɪ ˈmænɪdʒə tə kʌm/", definition: "Mời quản lý ra gặp khách", icon: "🧑‍💼" },
  ],
  handover: [
    { word: "Reservation book", phonetic: "/ˌrezəˈveɪʃn bʊk/", definition: "Sổ đặt bàn", icon: "📕" },
    { word: "Table plan", phonetic: "/ˈteɪbl plæn/", definition: "Sơ đồ xếp bàn", icon: "🗺️" },
    { word: "Allergy note", phonetic: "/ˈælədʒi nəʊt/", definition: "Ghi chú dị ứng", icon: "🥜" },
    { word: "Station checklist", phonetic: "/ˈsteɪʃn ˈtʃeklɪst/", definition: "Bảng kiểm tra khu phục vụ", icon: "📋" },
    { word: "Wine stock list", phonetic: "/waɪn stɒk lɪst/", definition: "Bảng kê rượu vang tồn", icon: "🍷" },
    { word: "Special guest note", phonetic: "/ˈspeʃl ɡest nəʊt/", definition: "Ghi chú khách đặc biệt", icon: "🌟" },
    { word: "Bar count", phonetic: "/bɑː kaʊnt/", definition: "Kiểm kê hàng quầy pha chế", icon: "🍸" },
    { word: "Breakage report", phonetic: "/ˈbreɪkɪdʒ rɪˈpɔːt/", definition: "Báo cáo đồ vỡ", icon: "💥" },
    { word: "Handover book", phonetic: "/ˈhændəʊvə bʊk/", definition: "Sổ bàn giao ca", icon: "📓" },
    { word: "Covers report", phonetic: "/ˈkʌvəz rɪˈpɔːt/", definition: "Báo cáo lượt khách phục vụ", icon: "📊" },
    { word: "Fridge temperature log", phonetic: "/frɪdʒ ˈtemprətʃə lɒɡ/", definition: "Sổ ghi nhiệt độ tủ lạnh", icon: "🌡️" },
    { word: "Sold-out list", phonetic: "/səʊld aʊt lɪst/", definition: "Danh sách món đã hết", icon: "🚫" },
  ],
  wrapUp: [
    { word: "Reservation time", phonetic: "/ˌrezəˈveɪʃn taɪm/", definition: "Giờ đặt bàn", icon: "⏰" },
    { word: "Final headcount", phonetic: "/ˈfaɪnl ˈhedkaʊnt/", definition: "Số khách chốt cuối cùng", icon: "👥" },
    { word: "Menu choice", phonetic: "/ˈmenjuː tʃɔɪs/", definition: "Lựa chọn thực đơn", icon: "📖" },
    { word: "Set menu price", phonetic: "/set ˈmenjuː praɪs/", definition: "Giá suất ăn cố định", icon: "💵" },
    { word: "Table layout", phonetic: "/ˈteɪbl ˈleɪaʊt/", definition: "Cách bố trí bàn", icon: "🪑" },
    { word: "Wine order", phonetic: "/waɪn ˈɔːdə/", definition: "Đơn gọi rượu vang", icon: "🍷" },
    { word: "Dietary request", phonetic: "/ˈdaɪətəri rɪˈkwest/", definition: "Yêu cầu về ăn kiêng", icon: "🥦" },
    { word: "Cake delivery time", phonetic: "/keɪk dɪˈlɪvəri taɪm/", definition: "Giờ mang bánh ra", icon: "🎂" },
    { word: "Private room setup", phonetic: "/ˈpraɪvət ruːm ˈsetʌp/", definition: "Cách bày phòng ăn riêng", icon: "🚪" },
    { word: "Deposit payment", phonetic: "/dɪˈpɒzɪt ˈpeɪmənt/", definition: "Việc thanh toán tiền cọc", icon: "💳" },
    { word: "Special occasion", phonetic: "/ˈspeʃl əˈkeɪʒn/", definition: "Dịp đặc biệt của khách", icon: "🎉" },
    { word: "Final bill", phonetic: "/ˈfaɪnl bɪl/", definition: "Hóa đơn cuối cùng", icon: "🧾" },
  ],
};

const HK_BANK: P3Bank = {
  upgrades: [
    { word: "Duvet upgrade", phonetic: "/ˈduːveɪ ˈʌpɡreɪd/", definition: "Nâng cấp chăn lông vũ", icon: "🛏️" },
    { word: "Memory foam topper", phonetic: "/ˈmeməri fəʊm ˈtɒpə/", definition: "Tấm đệm cao su non", icon: "🛌" },
    { word: "Premium toiletries", phonetic: "/ˈpriːmiəm ˈtɔɪlətriz/", definition: "Bộ đồ dùng phòng tắm cao cấp", icon: "🧴" },
    { word: "Evening turndown", phonetic: "/ˈiːvnɪŋ ˈtɜːndaʊn/", definition: "Chỉnh giường buổi tối", icon: "🌙" },
    { word: "Blackout curtains", phonetic: "/ˈblækaʊt ˈkɜːtnz/", definition: "Rèm chắn sáng", icon: "🪟" },
    { word: "Anti-allergy bedding", phonetic: "/ˈænti ˈælədʒi ˈbedɪŋ/", definition: "Bộ chăn ga chống dị ứng", icon: "🤧" },
    { word: "Silk pillowcase", phonetic: "/sɪlk ˈpɪləʊkeɪs/", definition: "Vỏ gối lụa", icon: "🪶" },
    { word: "Pillow spray", phonetic: "/ˈpɪləʊ spreɪ/", definition: "Xịt thơm gối", icon: "🌸" },
    { word: "Bath salt set", phonetic: "/bɑːθ sɔːlt set/", definition: "Bộ muối tắm", icon: "🛁" },
    { word: "Plush towel set", phonetic: "/plʌʃ ˈtaʊəl set/", definition: "Bộ khăn tắm dày cao cấp", icon: "🧖" },
    { word: "Air purifier", phonetic: "/eə ˈpjʊərɪfaɪə/", definition: "Máy lọc không khí", icon: "🌬️" },
    { word: "Baby bath set", phonetic: "/ˈbeɪbi bɑːθ set/", definition: "Bộ đồ tắm cho bé", icon: "🍼" },
  ],
  policies: [
    { word: "Lost key card fee", phonetic: "/lɒst kiː kɑːd fiː/", definition: "Phí mất thẻ phòng", icon: "🔑" },
    { word: "Damaged linen charge", phonetic: "/ˈdæmɪdʒd ˈlɪnɪn tʃɑːdʒ/", definition: "Phí làm hỏng khăn ga", icon: "🧺" },
    { word: "Rollaway bed charge", phonetic: "/ˈrəʊləweɪ bed tʃɑːdʒ/", definition: "Phí giường phụ kê thêm", icon: "🛏️" },
    { word: "Smoking penalty", phonetic: "/ˈsməʊkɪŋ ˈpenəlti/", definition: "Tiền phạt hút thuốc trong phòng", icon: "🚭" },
    { word: "Deep cleaning fee", phonetic: "/diːp ˈkliːnɪŋ fiː/", definition: "Phí vệ sinh chuyên sâu", icon: "🧼" },
    { word: "Late checkout fee", phonetic: "/leɪt ˈtʃekaʊt fiː/", definition: "Phí trả phòng muộn", icon: "🕐" },
    { word: "Missing towel charge", phonetic: "/ˈmɪsɪŋ ˈtaʊəl tʃɑːdʒ/", definition: "Phí mất khăn", icon: "🧻" },
    { word: "Minibar charge", phonetic: "/ˈmɪnibɑː tʃɑːdʒ/", definition: "Phí đồ trong minibar", icon: "🍫" },
    { word: "Pet cleaning fee", phonetic: "/pet ˈkliːnɪŋ fiː/", definition: "Phí vệ sinh do thú cưng", icon: "🐶" },
    { word: "Laundry price list", phonetic: "/ˈlɔːndri praɪs lɪst/", definition: "Bảng giá giặt là", icon: "💰" },
    { word: "Stain removal fee", phonetic: "/steɪn rɪˈmuːvl fiː/", definition: "Phí xử lý vết bẩn", icon: "🫧" },
    { word: "Lost property rule", phonetic: "/lɒst ˈprɒpəti ruːl/", definition: "Quy định về đồ khách bỏ quên", icon: "📕" },
  ],
  commitments: [
    { word: "Service your room", phonetic: "/ˈsɜːvɪs jɔː ruːm/", definition: "Dọn phòng cho quý khách", icon: "🧹" },
    { word: "Deliver the extra pillows", phonetic: "/dɪˈlɪvə ði ˈekstrə ˈpɪləʊz/", definition: "Mang thêm gối lên phòng", icon: "🛌" },
    { word: "Replace the bath mat", phonetic: "/rɪˈpleɪs ðə bɑːθ mæt/", definition: "Thay thảm chân phòng tắm", icon: "🧼" },
    { word: "Bring fresh towels up", phonetic: "/brɪŋ freʃ ˈtaʊəlz ʌp/", definition: "Mang khăn sạch lên phòng", icon: "🧻" },
    { word: "Vacuum the carpet again", phonetic: "/ˈvækjuːm ðə ˈkɑːpɪt əˈɡen/", definition: "Hút bụi thảm lần nữa", icon: "🌀" },
    { word: "Change the shower curtain", phonetic: "/tʃeɪndʒ ðə ˈʃaʊə ˈkɜːtn/", definition: "Thay rèm phòng tắm", icon: "🚿" },
    { word: "Empty the rubbish bins", phonetic: "/ˈempti ðə ˈrʌbɪʃ bɪnz/", definition: "Đổ các thùng rác trong phòng", icon: "🗑️" },
    { word: "Collect your laundry", phonetic: "/kəˈlekt jɔː ˈlɔːndri/", definition: "Lấy đồ giặt của quý khách", icon: "🧺" },
    { word: "Return your ironed shirt", phonetic: "/rɪˈtɜːn jɔːr ˈaɪənd ʃɜːt/", definition: "Trả lại áo đã ủi", icon: "👔" },
    { word: "Restock the minibar", phonetic: "/ˌriːˈstɒk ðə ˈmɪnibɑː/", definition: "Bổ sung đồ minibar", icon: "🍫" },
    { word: "Turn down your bed", phonetic: "/tɜːn daʊn jɔː bed/", definition: "Chỉnh giường buổi tối cho quý khách", icon: "🌙" },
    { word: "Send a room attendant", phonetic: "/send ə ruːm əˈtendənt/", definition: "Cử nhân viên buồng phòng lên", icon: "🔔" },
  ],
  partners: [
    { word: "Laundry team", phonetic: "/ˈlɔːndri tiːm/", definition: "Tổ giặt là", icon: "🧺" },
    { word: "Engineering team", phonetic: "/ˌendʒɪˈnɪərɪŋ tiːm/", definition: "Tổ kỹ thuật", icon: "🔧" },
    { word: "Front desk", phonetic: "/frʌnt desk/", definition: "Quầy lễ tân", icon: "🛎️" },
    { word: "Minibar attendant", phonetic: "/ˈmɪnibɑːr əˈtendənt/", definition: "Nhân viên phụ trách minibar", icon: "🍫" },
    { word: "Executive housekeeper", phonetic: "/ɪɡˈzekjətɪv ˈhaʊskiːpə/", definition: "Trưởng bộ phận buồng phòng", icon: "👔" },
    { word: "Turndown attendant", phonetic: "/ˈtɜːndaʊn əˈtendənt/", definition: "Nhân viên chỉnh giường buổi tối", icon: "🌙" },
    { word: "Night cleaner", phonetic: "/naɪt ˈkliːnə/", definition: "Nhân viên dọn ca đêm", icon: "🌃" },
    { word: "Linen store keeper", phonetic: "/ˈlɪnɪn stɔː ˈkiːpə/", definition: "Nhân viên kho khăn ga", icon: "📦" },
    { word: "Pest control team", phonetic: "/pest kənˈtrəʊl tiːm/", definition: "Đội diệt côn trùng", icon: "🐜" },
    { word: "Duty manager", phonetic: "/ˈdjuːti ˈmænɪdʒə/", definition: "Quản lý trực ca", icon: "🧑‍💼" },
    { word: "Room inspector", phonetic: "/ruːm ɪnˈspektə/", definition: "Nhân viên kiểm tra phòng", icon: "🔎" },
    { word: "Uniform room staff", phonetic: "/ˈjuːnɪfɔːm ruːm stɑːf/", definition: "Nhân viên kho đồng phục", icon: "🥼" },
  ],
  complaints: [
    { word: "Unmade bed", phonetic: "/ʌnˈmeɪd bed/", definition: "Giường chưa được dọn", icon: "🛏️" },
    { word: "Stained towel", phonetic: "/steɪnd ˈtaʊəl/", definition: "Khăn bị dính bẩn", icon: "🧻" },
    { word: "Missing amenity", phonetic: "/ˈmɪsɪŋ əˈmiːnəti/", definition: "Thiếu đồ dùng trong phòng", icon: "🧴" },
    { word: "Noisy vacuum cleaner", phonetic: "/ˈnɔɪzi ˈvækjuːm ˈkliːnə/", definition: "Máy hút bụi quá ồn", icon: "🔊" },
    { word: "Hair in the bathtub", phonetic: "/heər ɪn ðə ˈbɑːθtʌb/", definition: "Tóc còn sót trong bồn tắm", icon: "🛁" },
    { word: "Damp smell", phonetic: "/dæmp smel/", definition: "Mùi ẩm mốc", icon: "🤢" },
    { word: "Dirty carpet", phonetic: "/ˈdɜːti ˈkɑːpɪt/", definition: "Thảm bị bẩn", icon: "🟫" },
    { word: "Late cleaning", phonetic: "/leɪt ˈkliːnɪŋ/", definition: "Dọn phòng quá trễ", icon: "⏰" },
    { word: "Empty shampoo bottle", phonetic: "/ˈempti ʃæmˈpuː ˈbɒtl/", definition: "Chai dầu gội đã hết", icon: "🧼" },
    { word: "Broken hairdryer", phonetic: "/ˈbrəʊkən ˈheədraɪə/", definition: "Máy sấy tóc bị hỏng", icon: "💇" },
    { word: "Early morning knocking", phonetic: "/ˈɜːli ˈmɔːnɪŋ ˈnɒkɪŋ/", definition: "Gõ cửa quá sớm", icon: "✊" },
    { word: "Blocked shower drain", phonetic: "/blɒkt ˈʃaʊə dreɪn/", definition: "Cống thoát nước tắm bị tắc", icon: "🚿" },
  ],
  solutions: [
    { word: "Re-clean the bathroom", phonetic: "/riː ˈkliːn ðə ˈbɑːθruːm/", definition: "Dọn lại phòng tắm", icon: "🚿" },
    { word: "Change the bed sheets", phonetic: "/tʃeɪndʒ ðə bed ʃiːts/", definition: "Thay ga giường mới", icon: "🛏️" },
    { word: "Bring a replacement towel", phonetic: "/brɪŋ ə rɪˈpleɪsmənt ˈtaʊəl/", definition: "Mang khăn thay thế lên", icon: "🧻" },
    { word: "Move you to another room", phonetic: "/muːv juː tu əˈnʌðə ruːm/", definition: "Chuyển quý khách sang phòng khác", icon: "🔀" },
    { word: "Deep clean the carpet", phonetic: "/diːp kliːn ðə ˈkɑːpɪt/", definition: "Giặt sâu thảm phòng", icon: "🟫" },
    { word: "Replace the toiletries", phonetic: "/rɪˈpleɪs ðə ˈtɔɪlətriz/", definition: "Thay bộ đồ dùng phòng tắm", icon: "🧴" },
    { word: "Air out the room", phonetic: "/eər aʊt ðə ruːm/", definition: "Làm thoáng khí căn phòng", icon: "🪟" },
    { word: "Wash it free of charge", phonetic: "/wɒʃ ɪt friː əv tʃɑːdʒ/", definition: "Giặt miễn phí cho quý khách", icon: "🆓" },
    { word: "Rewash the towels tonight", phonetic: "/ˌriːˈwɒʃ ðə ˈtaʊəlz təˈnaɪt/", definition: "Giặt lại khăn ngay tối nay", icon: "🧺" },
    { word: "Clean while you are out", phonetic: "/kliːn waɪl juː ə aʊt/", definition: "Dọn phòng khi quý khách ra ngoài", icon: "🚪" },
    { word: "Use a quieter vacuum", phonetic: "/juːz ə ˈkwaɪətə ˈvækjuːm/", definition: "Dùng máy hút bụi êm hơn", icon: "🔇" },
    { word: "Remove the stain for you", phonetic: "/rɪˈmuːv ðə steɪn fə juː/", definition: "Xử lý vết bẩn giúp quý khách", icon: "🫧" },
  ],
  handover: [
    { word: "Room status board", phonetic: "/ruːm ˈsteɪtəs bɔːd/", definition: "Bảng trạng thái các phòng", icon: "🚦" },
    { word: "Out-of-order list", phonetic: "/aʊt əv ˈɔːdə lɪst/", definition: "Danh sách phòng đang hỏng", icon: "🚧" },
    { word: "Linen count", phonetic: "/ˈlɪnɪn kaʊnt/", definition: "Số lượng khăn ga còn lại", icon: "🧺" },
    { word: "Shift log book", phonetic: "/ʃɪft lɒɡ bʊk/", definition: "Sổ nhật ký ca làm", icon: "📒" },
    { word: "Discrepancy report", phonetic: "/dɪsˈkrepənsi rɪˈpɔːt/", definition: "Báo cáo phòng lệch trạng thái", icon: "📊" },
    { word: "Master key log", phonetic: "/ˈmɑːstə kiː lɒɡ/", definition: "Sổ theo dõi chìa khóa tổng", icon: "🔑" },
    { word: "Late checkout list", phonetic: "/leɪt ˈtʃekaʊt lɪst/", definition: "Danh sách phòng trả muộn", icon: "🕐" },
    { word: "Amenity stock sheet", phonetic: "/əˈmiːnəti stɒk ʃiːt/", definition: "Bảng kê vật tư còn trong kho", icon: "📦" },
    { word: "Turndown list", phonetic: "/ˈtɜːndaʊn lɪst/", definition: "Danh sách phòng chỉnh giường tối", icon: "🌙" },
    { word: "Trolley stock check", phonetic: "/ˈtrɒli stɒk tʃek/", definition: "Việc kiểm kê hàng trên xe đẩy", icon: "🛒" },
    { word: "Pending guest request", phonetic: "/ˈpendɪŋ ɡest rɪˈkwest/", definition: "Yêu cầu của khách chưa xong", icon: "⏳" },
    { word: "Lost item log", phonetic: "/lɒst ˈaɪtəm lɒɡ/", definition: "Sổ ghi đồ khách bỏ quên", icon: "🎒" },
  ],
  wrapUp: [
    { word: "Room assignment sheet", phonetic: "/ruːm əˈsaɪnmənt ʃiːt/", definition: "Bảng phân công phòng", icon: "📋" },
    { word: "Cleaning standard", phonetic: "/ˈkliːnɪŋ ˈstændəd/", definition: "Tiêu chuẩn dọn phòng", icon: "⭐" },
    { word: "Guest laundry order", phonetic: "/ɡest ˈlɔːndri ˈɔːdə/", definition: "Đơn giặt là của khách", icon: "🧺" },
    { word: "Linen delivery time", phonetic: "/ˈlɪnɪn dɪˈlɪvəri taɪm/", definition: "Giờ giao khăn ga sạch", icon: "🚚" },
    { word: "Extra bed request", phonetic: "/ˈekstrə bed rɪˈkwest/", definition: "Yêu cầu giường phụ", icon: "🛏️" },
    { word: "Room inspection result", phonetic: "/ruːm ɪnˈspekʃn rɪˈzʌlt/", definition: "Kết quả kiểm tra phòng", icon: "🔎" },
    { word: "Cleaning schedule", phonetic: "/ˈkliːnɪŋ ˈʃedjuːl/", definition: "Lịch dọn phòng trong ngày", icon: "📅" },
    { word: "Turndown time", phonetic: "/ˈtɜːndaʊn taɪm/", definition: "Giờ chỉnh giường buổi tối", icon: "🌙" },
    { word: "Pillow choice", phonetic: "/ˈpɪləʊ tʃɔɪs/", definition: "Loại gối khách chọn", icon: "🛌" },
    { word: "Damage charge amount", phonetic: "/ˈdæmɪdʒ tʃɑːdʒ əˈmaʊnt/", definition: "Số tiền phí hư hỏng", icon: "💵" },
    { word: "Do-not-disturb request", phonetic: "/duː nɒt dɪˈstɜːb rɪˈkwest/", definition: "Yêu cầu không làm phiền", icon: "🔕" },
    { word: "Checkout room priority", phonetic: "/ˈtʃekaʊt ruːm praɪˈɒrəti/", definition: "Ưu tiên phòng khách đã trả", icon: "❗" },
  ],
};

const SW_BANK: P3Bank = {
  upgrades: [
    { word: "Ninety-minute session", phonetic: "/ˈnaɪnti ˈmɪnɪt ˈseʃn/", definition: "Buổi trị liệu chín mươi phút", icon: "⏱️" },
    { word: "Hot stone upgrade", phonetic: "/hɒt stəʊn ˈʌpɡreɪd/", definition: "Nâng cấp đá nóng", icon: "🔥" },
    { word: "Couple's suite", phonetic: "/ˈkʌplz swiːt/", definition: "Phòng trị liệu đôi cao cấp", icon: "💑" },
    { word: "Salt body polish", phonetic: "/sɔːlt ˈbɒdi ˈpɒlɪʃ/", definition: "Liệu trình chà muối toàn thân", icon: "✨" },
    { word: "Aromatherapy massage", phonetic: "/ˌærəməˈθerəpi ˈmæsɑːʒ/", definition: "Xoa bóp bằng tinh dầu", icon: "🌸" },
    { word: "Private jacuzzi room", phonetic: "/ˈpraɪvət dʒəˈkuːzi ruːm/", definition: "Phòng bồn sục riêng", icon: "🛁" },
    { word: "Scalp treatment", phonetic: "/skælp ˈtriːtmənt/", definition: "Liệu trình chăm sóc da đầu", icon: "💆" },
    { word: "Herbal compress massage", phonetic: "/ˈhɜːbl ˈkɒmpres ˈmæsɑːʒ/", definition: "Xoa bóp chườm thảo dược", icon: "🌾" },
    { word: "Outdoor massage pavilion", phonetic: "/ˈaʊtdɔː ˈmæsɑːʒ pəˈvɪljən/", definition: "Chòi xoa bóp ngoài trời", icon: "🏝️" },
    { word: "Detox body wrap", phonetic: "/ˈdiːtɒks ˈbɒdi ræp/", definition: "Ủ thải độc toàn thân", icon: "🌿" },
    { word: "Full-day wellness pass", phonetic: "/fʊl deɪ ˈwelnəs pɑːs/", definition: "Vé chăm sóc sức khỏe cả ngày", icon: "🎟️" },
    { word: "Private yoga session", phonetic: "/ˈpraɪvət ˈjəʊɡə ˈseʃn/", definition: "Buổi tập yoga riêng", icon: "🧘" },
  ],
  policies: [
    { word: "Late arrival policy", phonetic: "/leɪt əˈraɪvl ˈpɒləsi/", definition: "Quy định khách đến trễ", icon: "⏰" },
    { word: "Cancellation window", phonetic: "/ˌkænsəˈleɪʃn ˈwɪndəʊ/", definition: "Thời hạn được phép hủy hẹn", icon: "🚫" },
    { word: "No-show fee", phonetic: "/nəʊ ʃəʊ fiː/", definition: "Phí không đến theo hẹn", icon: "💸" },
    { word: "Health declaration form", phonetic: "/helθ ˌdekləˈreɪʃn fɔːm/", definition: "Phiếu khai báo sức khỏe bắt buộc", icon: "📋" },
    { word: "Minimum age rule", phonetic: "/ˈmɪnɪməm eɪdʒ ruːl/", definition: "Quy định tuổi tối thiểu", icon: "🔞" },
    { word: "Session extension fee", phonetic: "/ˈseʃn ɪkˈstenʃn fiː/", definition: "Phí kéo dài buổi trị liệu", icon: "💳" },
    { word: "Swimwear rule", phonetic: "/ˈswɪmweə ruːl/", definition: "Quy định về đồ bơi", icon: "👙" },
    { word: "Silence rule", phonetic: "/ˈsaɪləns ruːl/", definition: "Quy định giữ yên lặng", icon: "🤫" },
    { word: "Locker deposit", phonetic: "/ˈlɒkə dɪˈpɒzɪt/", definition: "Tiền cọc tủ đồ", icon: "🔐" },
    { word: "Booking notice period", phonetic: "/ˈbʊkɪŋ ˈnəʊtɪs ˈpɪəriəd/", definition: "Thời gian báo trước khi đặt lịch", icon: "📅" },
    { word: "Medical clearance rule", phonetic: "/ˈmedɪkl ˈklɪərəns ruːl/", definition: "Quy định phải có xác nhận y tế", icon: "🩺" },
    { word: "Pool towel charge", phonetic: "/puːl ˈtaʊəl tʃɑːdʒ/", definition: "Phí khăn hồ bơi", icon: "🏊" },
  ],
  commitments: [
    { word: "Prepare the treatment room", phonetic: "/prɪˈpeə ðə ˈtriːtmənt ruːm/", definition: "Chuẩn bị phòng trị liệu", icon: "🛏️" },
    { word: "Confirm your therapist", phonetic: "/kənˈfɜːm jɔː ˈθerəpɪst/", definition: "Xác nhận kỹ thuật viên cho khách", icon: "✅" },
    { word: "Heat the herbal compress", phonetic: "/hiːt ðə ˈhɜːbl ˈkɒmpres/", definition: "Làm nóng túi chườm thảo dược", icon: "♨️" },
    { word: "Set up the foot bath", phonetic: "/set ʌp ðə fʊt bɑːθ/", definition: "Sắp sẵn chậu ngâm chân", icon: "🦶" },
    { word: "Call you at the pool", phonetic: "/kɔːl juː ət ðə puːl/", definition: "Gọi khách ở khu hồ bơi", icon: "📞" },
    { word: "Reserve the couple's suite", phonetic: "/rɪˈzɜːv ðə ˈkʌplz swiːt/", definition: "Giữ phòng trị liệu đôi", icon: "💑" },
    { word: "Update the treatment schedule", phonetic: "/ˈʌpdeɪt ðə ˈtriːtmənt ˈʃedjuːl/", definition: "Cập nhật lịch trị liệu", icon: "📅" },
    { word: "Refill the oil bottles", phonetic: "/ˌriːˈfɪl ði ɔɪl ˈbɒtlz/", definition: "Châm đầy các chai tinh dầu", icon: "🫗" },
    { word: "Send the health form", phonetic: "/send ðə helθ fɔːm/", definition: "Gửi phiếu khai sức khỏe", icon: "📋" },
    { word: "Book your next visit", phonetic: "/bʊk jɔː nekst ˈvɪzɪt/", definition: "Đặt lịch lần sau cho khách", icon: "📔" },
    { word: "Check the steam room", phonetic: "/tʃek ðə stiːm ruːm/", definition: "Kiểm tra phòng xông hơi", icon: "🌫️" },
    { word: "Lay out fresh robes", phonetic: "/leɪ aʊt freʃ rəʊbz/", definition: "Bày sẵn áo choàng sạch", icon: "🥋" },
  ],
  partners: [
    { word: "Spa therapists", phonetic: "/spɑː ˈθerəpɪsts/", definition: "Các kỹ thuật viên spa", icon: "💆" },
    { word: "Pool attendants", phonetic: "/puːl əˈtendənts/", definition: "Nhân viên trực hồ bơi", icon: "🏊" },
    { word: "Gym instructors", phonetic: "/dʒɪm ɪnˈstrʌktəz/", definition: "Huấn luyện viên phòng tập", icon: "🏋️" },
    { word: "Sauna attendants", phonetic: "/ˈsɔːnə əˈtendənts/", definition: "Nhân viên trực phòng xông hơi", icon: "🌫️" },
    { word: "Nail technicians", phonetic: "/neɪl tekˈnɪʃnz/", definition: "Thợ làm móng", icon: "💅" },
    { word: "Beauty therapists", phonetic: "/ˈbjuːti ˈθerəpɪsts/", definition: "Kỹ thuật viên chăm sóc sắc đẹp", icon: "💄" },
    { word: "Wellness consultants", phonetic: "/ˈwelnəs kənˈsʌltənts/", definition: "Chuyên viên tư vấn sức khỏe", icon: "🧘" },
    { word: "Yoga teachers", phonetic: "/ˈjəʊɡə ˈtiːtʃəz/", definition: "Giáo viên yoga", icon: "🪷" },
    { word: "Spa supervisors", phonetic: "/spɑː ˈsuːpəvaɪzəz/", definition: "Các giám sát viên spa", icon: "👔" },
    { word: "Spa product suppliers", phonetic: "/spɑː ˈprɒdʌkt səˈplaɪəz/", definition: "Nhà cung cấp sản phẩm spa", icon: "📦" },
    { word: "Spa linen staff", phonetic: "/spɑː ˈlɪnɪn stɑːf/", definition: "Nhân viên phụ trách đồ vải spa", icon: "🧺" },
    { word: "Hotel nurses", phonetic: "/həʊˈtel ˈnɜːsɪz/", definition: "Y tá của khách sạn", icon: "🩺" },
  ],
  complaints: [
    { word: "Cold treatment room", phonetic: "/kəʊld ˈtriːtmənt ruːm/", definition: "Phòng trị liệu bị lạnh", icon: "🥶" },
    { word: "Strong hand pressure", phonetic: "/strɒŋ hænd ˈpreʃə/", definition: "Lực tay quá mạnh", icon: "💪" },
    { word: "Late therapist", phonetic: "/leɪt ˈθerəpɪst/", definition: "Kỹ thuật viên đến trễ", icon: "⏰" },
    { word: "Short treatment", phonetic: "/ʃɔːt ˈtriːtmənt/", definition: "Liệu trình bị làm ngắn hơn", icon: "⏳" },
    { word: "Strong oil smell", phonetic: "/strɒŋ ɔɪl smel/", definition: "Mùi tinh dầu quá nồng", icon: "👃" },
    { word: "Loud spa music", phonetic: "/laʊd spɑː ˈmjuːzɪk/", definition: "Nhạc trong spa quá to", icon: "🔊" },
    { word: "Dirty changing room", phonetic: "/ˈdɜːti ˈtʃeɪndʒɪŋ ruːm/", definition: "Phòng thay đồ bẩn", icon: "🚻" },
    { word: "Cold pool water", phonetic: "/kəʊld puːl ˈwɔːtə/", definition: "Nước hồ bơi lạnh", icon: "💧" },
    { word: "Skin irritation", phonetic: "/skɪn ˌɪrɪˈteɪʃn/", definition: "Da bị kích ứng", icon: "🔴" },
    { word: "Long waiting time", phonetic: "/lɒŋ ˈweɪtɪŋ taɪm/", definition: "Thời gian chờ quá lâu", icon: "⌛" },
    { word: "Wrong treatment booking", phonetic: "/rɒŋ ˈtriːtmənt ˈbʊkɪŋ/", definition: "Đặt nhầm liệu trình", icon: "❌" },
    { word: "Broken sauna heater", phonetic: "/ˈbrəʊkən ˈsɔːnə ˈhiːtə/", definition: "Máy sưởi phòng xông bị hỏng", icon: "🔧" },
  ],
  solutions: [
    { word: "Extend the session", phonetic: "/ɪkˈstend ðə ˈseʃn/", definition: "Kéo dài buổi trị liệu", icon: "⏱️" },
    { word: "Change your therapist", phonetic: "/tʃeɪndʒ jɔː ˈθerəpɪst/", definition: "Đổi kỹ thuật viên khác", icon: "🔄" },
    { word: "Reschedule at no charge", phonetic: "/ˌriːˈʃedjuːl ət nəʊ tʃɑːdʒ/", definition: "Dời lịch mà không tính phí", icon: "🆓" },
    { word: "Turn up the heating", phonetic: "/tɜːn ʌp ðə ˈhiːtɪŋ/", definition: "Tăng nhiệt độ trong phòng", icon: "🌡️" },
    { word: "Use a lighter pressure", phonetic: "/juːz ə ˈlaɪtə ˈpreʃə/", definition: "Dùng lực nhẹ hơn", icon: "🪶" },
    { word: "Change the treatment room", phonetic: "/tʃeɪndʒ ðə ˈtriːtmənt ruːm/", definition: "Đổi sang phòng trị liệu khác", icon: "🚪" },
    { word: "Offer a free upgrade", phonetic: "/ˈɒfə ə friː ˈʌpɡreɪd/", definition: "Tặng một lần nâng cấp miễn phí", icon: "🎁" },
    { word: "Lower the music volume", phonetic: "/ˈləʊə ðə ˈmjuːzɪk ˈvɒljuːm/", definition: "Giảm âm lượng nhạc", icon: "🔉" },
    { word: "Change the oil blend", phonetic: "/tʃeɪndʒ ði ɔɪl blend/", definition: "Đổi loại tinh dầu pha", icon: "🫗" },
    { word: "Add ten free minutes", phonetic: "/æd ten friː ˈmɪnɪts/", definition: "Cộng thêm mười phút miễn phí", icon: "➕" },
    { word: "Bring a warm blanket", phonetic: "/brɪŋ ə wɔːm ˈblæŋkɪt/", definition: "Mang thêm chăn ấm", icon: "🧣" },
    { word: "Refund the extra charge", phonetic: "/ˈriːfʌnd ði ˈekstrə tʃɑːdʒ/", definition: "Hoàn lại khoản phí thu thêm", icon: "💰" },
  ],
  handover: [
    { word: "Treatment schedule", phonetic: "/ˈtriːtmənt ˈʃedjuːl/", definition: "Lịch trị liệu trong ngày", icon: "📅" },
    { word: "Therapist roster", phonetic: "/ˈθerəpɪst ˈrɒstə/", definition: "Bảng phân ca kỹ thuật viên", icon: "🧑‍⚕️" },
    { word: "Product stock list", phonetic: "/ˈprɒdʌkt stɒk lɪst/", definition: "Danh sách hàng tồn của spa", icon: "📦" },
    { word: "Treatment room checklist", phonetic: "/ˈtriːtmənt ruːm ˈtʃeklɪst/", definition: "Bảng kiểm phòng trị liệu", icon: "✅" },
    { word: "Pool water log", phonetic: "/puːl ˈwɔːtə lɒɡ/", definition: "Sổ theo dõi nước hồ bơi", icon: "💧" },
    { word: "Towel count", phonetic: "/ˈtaʊəl kaʊnt/", definition: "Số khăn đã kiểm", icon: "🧻" },
    { word: "Guest allergy note", phonetic: "/ɡest ˈælədʒi nəʊt/", definition: "Ghi chú dị ứng của khách", icon: "⚠️" },
    { word: "Linen order", phonetic: "/ˈlɪnɪn ˈɔːdə/", definition: "Đơn đặt đồ vải", icon: "🧺" },
    { word: "Walk-in list", phonetic: "/wɔːk ɪn lɪst/", definition: "Danh sách khách đến không hẹn", icon: "🚶" },
    { word: "Sauna maintenance log", phonetic: "/ˈsɔːnə ˈmeɪntənəns lɒɡ/", definition: "Sổ bảo trì phòng xông hơi", icon: "🔧" },
    { word: "Next day booking list", phonetic: "/nekst deɪ ˈbʊkɪŋ lɪst/", definition: "Danh sách lịch hẹn ngày mai", icon: "🗓️" },
    { word: "Locker key count", phonetic: "/ˈlɒkə kiː kaʊnt/", definition: "Số chìa khóa tủ đồ", icon: "🔑" },
  ],
  wrapUp: [
    { word: "Session length", phonetic: "/ˈseʃn leŋθ/", definition: "Thời lượng buổi trị liệu", icon: "⏱️" },
    { word: "Therapist gender", phonetic: "/ˈθerəpɪst ˈdʒendə/", definition: "Giới tính của kỹ thuật viên", icon: "🧑" },
    { word: "Treatment start time", phonetic: "/ˈtriːtmənt stɑːt taɪm/", definition: "Giờ bắt đầu liệu trình", icon: "🕐" },
    { word: "Massage oil choice", phonetic: "/ˈmæsɑːʒ ɔɪl tʃɔɪs/", definition: "Lựa chọn dầu xoa bóp", icon: "🫗" },
    { word: "Upgrade price", phonetic: "/ˈʌpɡreɪd praɪs/", definition: "Giá của gói nâng cấp", icon: "💰" },
    { word: "Cancellation deadline", phonetic: "/ˌkænsəˈleɪʃn ˈdedlaɪn/", definition: "Hạn chót được hủy hẹn", icon: "⏳" },
    { word: "Health form answers", phonetic: "/helθ fɔːm ˈɑːnsəz/", definition: "Các câu trả lời trong phiếu sức khỏe", icon: "📋" },
    { word: "Locker number", phonetic: "/ˈlɒkə ˈnʌmbə/", definition: "Số tủ đồ của khách", icon: "🔑" },
    { word: "Pressure preference", phonetic: "/ˈpreʃə ˈprefrəns/", definition: "Mức lực khách mong muốn", icon: "💪" },
    { word: "Pool opening hours", phonetic: "/puːl ˈəʊpnɪŋ ˈaʊəz/", definition: "Giờ mở cửa hồ bơi", icon: "🏊" },
    { word: "Sensitive area", phonetic: "/ˈsensətɪv ˈeəriə/", definition: "Vùng cơ thể cần tránh", icon: "🚫" },
    { word: "Next appointment date", phonetic: "/nekst əˈpɔɪntmənt deɪt/", definition: "Ngày hẹn kế tiếp", icon: "📅" },
  ],
};

const GR_BANK: P3Bank = {
  upgrades: [
    { word: "Club floor room", phonetic: "/klʌb flɔː ruːm/", definition: "Phòng tầng câu lạc bộ", icon: "🏢" },
    { word: "Executive suite", phonetic: "/ɪɡˈzekjətɪv swiːt/", definition: "Phòng hạng sang rộng rãi", icon: "🛏️" },
    { word: "Airport transfer", phonetic: "/ˈeəpɔːt ˈtrænsfɜː/", definition: "Dịch vụ đưa đón sân bay", icon: "🚐" },
    { word: "Limousine pick-up", phonetic: "/ˈlɪməziːn ˈpɪk ʌp/", definition: "Xe hạng sang đón khách", icon: "🚙" },
    { word: "Private check-in", phonetic: "/ˈpraɪvət ˈtʃek ɪn/", definition: "Làm thủ tục riêng cho khách", icon: "🔑" },
    { word: "Butler service", phonetic: "/ˈbʌtlə ˈsɜːvɪs/", definition: "Dịch vụ quản gia riêng", icon: "🤵" },
    { word: "Lounge breakfast", phonetic: "/laʊndʒ ˈbrekfəst/", definition: "Bữa sáng tại phòng chờ", icon: "🥐" },
    { word: "Evening cocktail hour", phonetic: "/ˈiːvnɪŋ ˈkɒkteɪl ˈaʊə/", definition: "Giờ mời đồ uống buổi tối", icon: "🍸" },
    { word: "Anniversary set-up", phonetic: "/ˌænɪˈvɜːsəri ˈsetʌp/", definition: "Trang trí mừng ngày kỷ niệm", icon: "💐" },
    { word: "Welcome amenity", phonetic: "/ˈwelkəm əˈmiːnəti/", definition: "Quà chào đón đặt tại phòng", icon: "🎁" },
    { word: "Pillow menu", phonetic: "/ˈpɪləʊ ˈmenjuː/", definition: "Danh mục gối cho khách chọn", icon: "🛌" },
    { word: "Spa credit", phonetic: "/spɑː ˈkredɪt/", definition: "Phiếu tiêu dùng tại spa", icon: "💳" },
  ],
  policies: [
    { word: "Membership tier rule", phonetic: "/ˈmembəʃɪp tɪə ruːl/", definition: "Quy định hạng hội viên", icon: "🏅" },
    { word: "Benefit condition", phonetic: "/ˈbenɪfɪt kənˈdɪʃn/", definition: "Điều kiện hưởng quyền lợi", icon: "✅" },
    { word: "Blackout period", phonetic: "/ˈblækaʊt ˈpɪəriəd/", definition: "Giai đoạn ngưng ưu đãi", icon: "📆" },
    { word: "Consent form", phonetic: "/kənˈsent fɔːm/", definition: "Phiếu khách đồng ý lưu thông tin", icon: "✍️" },
    { word: "Points expiry rule", phonetic: "/pɔɪnts ɪkˈspaɪəri ruːl/", definition: "Quy định hạn dùng điểm", icon: "⌛" },
    { word: "Lounge dress code", phonetic: "/laʊndʒ dres kəʊd/", definition: "Quy định trang phục phòng chờ", icon: "👔" },
    { word: "Tier renewal rule", phonetic: "/tɪə rɪˈnjuːəl ruːl/", definition: "Quy định gia hạn cấp hạng", icon: "🔄" },
    { word: "Member rate", phonetic: "/ˈmembə reɪt/", definition: "Giá dành cho hội viên", icon: "💵" },
    { word: "Guest privacy rule", phonetic: "/ɡest ˈprɪvəsi ruːl/", definition: "Quy định bảo mật thông tin khách", icon: "🔒" },
    { word: "Two-night minimum", phonetic: "/tuː naɪt ˈmɪnɪməm/", definition: "Ở tối thiểu hai đêm", icon: "🌙" },
    { word: "Benefit transfer rule", phonetic: "/ˈbenɪfɪt ˈtrænsfɜː ruːl/", definition: "Quy định nhượng quyền lợi", icon: "🚫" },
    { word: "Guest limit", phonetic: "/ɡest ˈlɪmɪt/", definition: "Giới hạn số khách đi kèm", icon: "👥" },
  ],
  commitments: [
    { word: "Call you back personally", phonetic: "/kɔːl juː bæk ˈpɜːsənəli/", definition: "Đích thân gọi lại cho quý khách", icon: "📞" },
    { word: "Confirm the upgrade", phonetic: "/kənˈfɜːm ði ˈʌpɡreɪd/", definition: "Xác nhận việc nâng hạng", icon: "⬆️" },
    { word: "Update your guest file", phonetic: "/ʌpˈdeɪt jɔː ɡest faɪl/", definition: "Cập nhật hồ sơ của quý khách", icon: "🗂️" },
    { word: "Check with the lounge", phonetic: "/tʃek wɪð ðə laʊndʒ/", definition: "Hỏi lại phòng chờ", icon: "🛋️" },
    { word: "Send you a message", phonetic: "/send juː ə ˈmesɪdʒ/", definition: "Nhắn tin cho quý khách", icon: "💬" },
    { word: "Follow up with the kitchen", phonetic: "/ˈfɒləʊ ʌp wɪð ðə ˈkɪtʃɪn/", definition: "Theo dõi lại với bếp", icon: "👨‍🍳" },
    { word: "Speak to the duty manager", phonetic: "/spiːk tə ðə ˈdjuːti ˈmænɪdʒə/", definition: "Trao đổi với quản lý trực", icon: "👔" },
    { word: "Note it in your profile", phonetic: "/nəʊt ɪt ɪn jɔː ˈprəʊfaɪl/", definition: "Ghi vào hồ sơ của quý khách", icon: "📝" },
    { word: "Reserve your lounge table", phonetic: "/rɪˈzɜːv jɔː laʊndʒ ˈteɪbl/", definition: "Giữ bàn phòng chờ cho khách", icon: "🪑" },
    { word: "Escort you to your room", phonetic: "/ɪˈskɔːt juː tə jɔː ruːm/", definition: "Đưa quý khách lên phòng", icon: "🚶" },
    { word: "Arrange the transfer myself", phonetic: "/əˈreɪndʒ ðə ˈtrænsfɜː maɪˈself/", definition: "Tự tay sắp xếp xe đưa đón", icon: "🚐" },
    { word: "Bring your welcome gift", phonetic: "/brɪŋ jɔː ˈwelkəm ɡɪft/", definition: "Mang quà chào đón tới cho khách", icon: "🎁" },
  ],
  partners: [
    { word: "Front office", phonetic: "/frʌnt ˈɒfɪs/", definition: "Bộ phận tiền sảnh", icon: "🛎️" },
    { word: "Concierge desk", phonetic: "/ˈkɒnsieəʒ desk/", definition: "Quầy hỗ trợ khách", icon: "🧭" },
    { word: "Duty manager", phonetic: "/ˈdjuːti ˈmænɪdʒə/", definition: "Quản lý trực ca", icon: "👔" },
    { word: "Housekeeping supervisor", phonetic: "/ˈhaʊskiːpɪŋ ˈsuːpəvaɪzə/", definition: "Giám sát buồng phòng", icon: "🧹" },
    { word: "Executive chef", phonetic: "/ɪɡˈzekjətɪv ʃef/", definition: "Bếp trưởng điều hành", icon: "👨‍🍳" },
    { word: "Lounge team", phonetic: "/laʊndʒ tiːm/", definition: "Tổ phòng chờ", icon: "🛋️" },
    { word: "Reservations team", phonetic: "/ˌrezəˈveɪʃnz tiːm/", definition: "Bộ phận đặt phòng", icon: "📇" },
    { word: "Loyalty office", phonetic: "/ˈlɔɪəlti ˈɒfɪs/", definition: "Bộ phận khách hàng thân thiết", icon: "🏅" },
    { word: "Airport representative", phonetic: "/ˈeəpɔːt ˌreprɪˈzentətɪv/", definition: "Nhân viên đại diện tại sân bay", icon: "✈️" },
    { word: "Flower team", phonetic: "/ˈflaʊə tiːm/", definition: "Tổ cắm hoa", icon: "💐" },
    { word: "Pastry chef", phonetic: "/ˈpeɪstri ʃef/", definition: "Thợ làm bánh ngọt", icon: "🎂" },
    { word: "Bell desk", phonetic: "/bel desk/", definition: "Quầy hành lý", icon: "🧳" },
  ],
  complaints: [
    { word: "Broken promise", phonetic: "/ˈbrəʊkən ˈprɒmɪs/", definition: "Lời hứa không được giữ", icon: "💔" },
    { word: "Missing benefit", phonetic: "/ˈmɪsɪŋ ˈbenɪfɪt/", definition: "Quyền lợi bị bỏ sót", icon: "❌" },
    { word: "Ignored request", phonetic: "/ɪɡˈnɔːd rɪˈkwest/", definition: "Yêu cầu bị bỏ qua", icon: "🙉" },
    { word: "Impersonal service", phonetic: "/ɪmˈpɜːsənl ˈsɜːvɪs/", definition: "Phục vụ thiếu sự quan tâm", icon: "🥶" },
    { word: "Wrong name on the card", phonetic: "/rɒŋ neɪm ɒn ðə kɑːd/", definition: "Ghi sai tên khách trên thiệp", icon: "🏷️" },
    { word: "Late amenity delivery", phonetic: "/leɪt əˈmiːnəti dɪˈlɪvəri/", definition: "Quà lên phòng quá muộn", icon: "⏰" },
    { word: "Refused upgrade", phonetic: "/rɪˈfjuːzd ˈʌpɡreɪd/", definition: "Bị từ chối nâng hạng phòng", icon: "⬇️" },
    { word: "Lost preference note", phonetic: "/lɒst ˈprefrəns nəʊt/", definition: "Ghi chú sở thích bị thất lạc", icon: "📄" },
    { word: "Forgotten birthday", phonetic: "/fəˈɡɒtn ˈbɜːθdeɪ/", definition: "Quên mất sinh nhật của khách", icon: "🎂" },
    { word: "Long wait at check-in", phonetic: "/lɒŋ weɪt ət ˈtʃek ɪn/", definition: "Chờ lâu khi nhận phòng", icon: "🕰️" },
    { word: "Crowded lounge", phonetic: "/ˈkraʊdɪd laʊndʒ/", definition: "Phòng chờ quá đông", icon: "👥" },
    { word: "Wrong points balance", phonetic: "/rɒŋ pɔɪnts ˈbæləns/", definition: "Sai số điểm tích lũy", icon: "⭐" },
  ],
  solutions: [
    { word: "Arrange a room upgrade", phonetic: "/əˈreɪndʒ ə ruːm ˈʌpɡreɪd/", definition: "Sắp xếp nâng hạng phòng", icon: "⬆️" },
    { word: "Send a written apology", phonetic: "/send ə ˈrɪtn əˈpɒlədʒi/", definition: "Gửi thư xin lỗi tới khách", icon: "✉️" },
    { word: "Invite you to the lounge", phonetic: "/ɪnˈvaɪt juː tə ðə laʊndʒ/", definition: "Mời quý khách lên phòng chờ", icon: "🛋️" },
    { word: "Add the missing points", phonetic: "/æd ðə ˈmɪsɪŋ pɔɪnts/", definition: "Cộng bù số điểm còn thiếu", icon: "⭐" },
    { word: "Arrange a private dinner", phonetic: "/əˈreɪndʒ ə ˈpraɪvət ˈdɪnə/", definition: "Sắp xếp bữa tối riêng", icon: "🍽️" },
    { word: "Reprint the welcome card", phonetic: "/ˌriːˈprɪnt ðə ˈwelkəm kɑːd/", definition: "In lại thiệp chào đón", icon: "🖨️" },
    { word: "Deliver the amenity now", phonetic: "/dɪˈlɪvə ði əˈmiːnəti naʊ/", definition: "Đưa quà lên phòng ngay", icon: "🎁" },
    { word: "Bring the manager to you", phonetic: "/brɪŋ ðə ˈmænɪdʒə tə juː/", definition: "Mời quản lý tới gặp quý khách", icon: "👔" },
    { word: "Extend your late check-out", phonetic: "/ɪkˈstend jɔː leɪt ˈtʃekaʊt/", definition: "Gia hạn thêm giờ trả phòng", icon: "🕐" },
    { word: "Move you to a suite", phonetic: "/muːv juː tə ə swiːt/", definition: "Chuyển quý khách sang phòng hạng sang", icon: "🛏️" },
    { word: "Repeat the set-up tomorrow", phonetic: "/rɪˈpiːt ðə ˈsetʌp təˈmɒrəʊ/", definition: "Làm lại phần trang trí vào mai", icon: "🔁" },
    { word: "Cancel the extra charge", phonetic: "/ˈkænsl ði ˈekstrə tʃɑːdʒ/", definition: "Hủy khoản phụ thu", icon: "💸" },
  ],
  handover: [
    { word: "VIP arrival list", phonetic: "/ˌviː aɪ ˈpiː əˈraɪvl lɪst/", definition: "Danh sách khách VIP sắp đến", icon: "🌟" },
    { word: "Guest preference file", phonetic: "/ɡest ˈprefrəns faɪl/", definition: "Hồ sơ sở thích của khách", icon: "🗂️" },
    { word: "Open recovery case", phonetic: "/ˈəʊpən rɪˈkʌvəri keɪs/", definition: "Vụ việc chưa xử lý xong", icon: "🩹" },
    { word: "Amenity delivery list", phonetic: "/əˈmiːnəti dɪˈlɪvəri lɪst/", definition: "Danh sách quà cần gửi lên phòng", icon: "🎁" },
    { word: "Shift handover book", phonetic: "/ʃɪft ˈhændəʊvə bʊk/", definition: "Sổ bàn giao ca", icon: "📓" },
    { word: "Complaint log", phonetic: "/kəmˈpleɪnt lɒɡ/", definition: "Sổ ghi phàn nàn của khách", icon: "📕" },
    { word: "Birthday calendar", phonetic: "/ˈbɜːθdeɪ ˈkælɪndə/", definition: "Lịch sinh nhật của khách", icon: "🎂" },
    { word: "Departure schedule", phonetic: "/dɪˈpɑːtʃə ˈʃedjuːl/", definition: "Lịch khách rời khách sạn", icon: "🧳" },
    { word: "Upgrade waiting list", phonetic: "/ˈʌpɡreɪd ˈweɪtɪŋ lɪst/", definition: "Danh sách chờ nâng hạng", icon: "📋" },
    { word: "Follow-up note", phonetic: "/ˈfɒləʊ ʌp nəʊt/", definition: "Ghi chú việc cần theo dõi tiếp", icon: "✅" },
    { word: "Set-up checklist", phonetic: "/ˈsetʌp ˈtʃeklɪst/", definition: "Bảng kiểm phần trang trí phòng", icon: "📝" },
    { word: "Lounge duty roster", phonetic: "/laʊndʒ ˈdjuːti ˈrɒstə/", definition: "Lịch trực phòng chờ", icon: "🗓️" },
  ],
  wrapUp: [
    { word: "Upgrade request", phonetic: "/ˈʌpɡreɪd rɪˈkwest/", definition: "Yêu cầu nâng hạng phòng", icon: "⬆️" },
    { word: "Transfer time", phonetic: "/ˈtrænsfɜː taɪm/", definition: "Giờ xe đưa đón", icon: "🚐" },
    { word: "Lounge booking", phonetic: "/laʊndʒ ˈbʊkɪŋ/", definition: "Lượt đặt chỗ phòng chờ", icon: "🛋️" },
    { word: "Cake message", phonetic: "/keɪk ˈmesɪdʒ/", definition: "Lời chúc viết trên bánh", icon: "🎂" },
    { word: "Tier level", phonetic: "/tɪə ˈlevl/", definition: "Cấp hạng hội viên", icon: "🏅" },
    { word: "Benefit list", phonetic: "/ˈbenɪfɪt lɪst/", definition: "Danh mục quyền lợi", icon: "🎁" },
    { word: "Apology letter", phonetic: "/əˈpɒlədʒi ˈletə/", definition: "Thư xin lỗi", icon: "✉️" },
    { word: "Recovery plan", phonetic: "/rɪˈkʌvəri plæn/", definition: "Phương án khắc phục", icon: "🩹" },
    { word: "Arrival time", phonetic: "/əˈraɪvl taɪm/", definition: "Giờ khách tới", icon: "🕐" },
    { word: "Guest name spelling", phonetic: "/ɡest neɪm ˈspelɪŋ/", definition: "Cách viết tên khách", icon: "🔤" },
    { word: "Room preference", phonetic: "/ruːm ˈprefrəns/", definition: "Sở thích về phòng", icon: "🛏️" },
    { word: "Anniversary date", phonetic: "/ˌænɪˈvɜːsəri deɪt/", definition: "Ngày kỷ niệm của khách", icon: "💐" },
  ],
};

const BO_BANK: P3Bank = {
  upgrades: [
    { word: "Extended payment terms", phonetic: "/ɪkˈstendɪd ˈpeɪmənt tɜːmz/", definition: "Kỳ hạn thanh toán kéo dài", icon: "📆" },
    { word: "Complimentary meeting room", phonetic: "/ˌkɒmplɪˈmentri ˈmiːtɪŋ ruːm/", definition: "Phòng họp miễn phí", icon: "🎁" },
    { word: "Extra room night", phonetic: "/ˈekstrə ruːm naɪt/", definition: "Đêm phòng tặng thêm", icon: "🌙" },
    { word: "Flexible release date", phonetic: "/ˈfleksəbl rɪˈliːs deɪt/", definition: "Ngày trả phòng linh hoạt", icon: "📅" },
    { word: "Volume discount", phonetic: "/ˈvɒljuːm ˈdɪskaʊnt/", definition: "Chiết khấu theo số lượng", icon: "📉" },
    { word: "Free airport transfer", phonetic: "/friː ˈeəpɔːt ˈtrænsfɜː/", definition: "Đưa đón sân bay miễn phí", icon: "🚐" },
    { word: "Bigger allotment", phonetic: "/ˈbɪɡə əˈlɒtmənt/", definition: "Số phòng giữ chỗ nhiều hơn", icon: "🛏️" },
    { word: "Priority confirmation", phonetic: "/praɪˈɒrəti ˌkɒnfəˈmeɪʃn/", definition: "Ưu tiên xác nhận", icon: "⚡" },
    { word: "Dedicated account manager", phonetic: "/ˈdedɪkeɪtɪd əˈkaʊnt ˈmænɪdʒə/", definition: "Nhân viên phụ trách riêng", icon: "🧑‍💼" },
    { word: "Free late check-out", phonetic: "/friː leɪt ˈtʃek aʊt/", definition: "Trả phòng muộn miễn phí", icon: "🕛" },
    { word: "Bonus loyalty points", phonetic: "/ˈbəʊnəs ˈlɔɪəlti pɔɪnts/", definition: "Điểm thưởng khách hàng thân thiết", icon: "⭐" },
    { word: "Free room upgrade", phonetic: "/friː ruːm ˈʌpɡreɪd/", definition: "Nâng hạng phòng miễn phí", icon: "⬆️" },
  ],
  policies: [
    { word: "Deposit policy", phonetic: "/dɪˈpɒzɪt ˈpɒləsi/", definition: "Chính sách đặt cọc", icon: "💰" },
    { word: "Cancellation clause", phonetic: "/ˌkænsəˈleɪʃn klɔːz/", definition: "Điều khoản hủy", icon: "✂️" },
    { word: "Credit limit", phonetic: "/ˈkredɪt ˈlɪmɪt/", definition: "Hạn mức công nợ", icon: "💳" },
    { word: "Tax invoice rule", phonetic: "/tæks ˈɪnvɔɪs ruːl/", definition: "Quy định xuất hóa đơn thuế", icon: "🧾" },
    { word: "Late payment charge", phonetic: "/leɪt ˈpeɪmənt tʃɑːdʒ/", definition: "Phí thanh toán trễ hạn", icon: "⏰" },
    { word: "Minimum spend", phonetic: "/ˈmɪnɪməm spend/", definition: "Mức chi tiêu tối thiểu", icon: "📊" },
    { word: "Service charge", phonetic: "/ˈsɜːvɪs tʃɑːdʒ/", definition: "Phí phục vụ", icon: "💵" },
    { word: "No-show fee", phonetic: "/ˈnəʊ ʃəʊ fiː/", definition: "Phí khách không đến", icon: "🚫" },
    { word: "Amendment fee", phonetic: "/əˈmendmənt fiː/", definition: "Phí sửa đổi hợp đồng", icon: "✏️" },
    { word: "Group booking policy", phonetic: "/ɡruːp ˈbʊkɪŋ ˈpɒləsi/", definition: "Chính sách đặt đoàn", icon: "👥" },
    { word: "Refund policy", phonetic: "/ˈriːfʌnd ˈpɒləsi/", definition: "Chính sách hoàn tiền", icon: "🔁" },
    { word: "Purchase approval limit", phonetic: "/ˈpɜːtʃəs əˈpruːvl ˈlɪmɪt/", definition: "Hạn mức duyệt mua hàng", icon: "🔐" },
  ],
  commitments: [
    { word: "Send the quotation", phonetic: "/send ðə kwəʊˈteɪʃn/", definition: "Gửi báo giá", icon: "📤" },
    { word: "Issue the invoice", phonetic: "/ˈɪʃuː ði ˈɪnvɔɪs/", definition: "Xuất hóa đơn", icon: "🧾" },
    { word: "Confirm the booking", phonetic: "/kənˈfɜːm ðə ˈbʊkɪŋ/", definition: "Xác nhận đặt chỗ", icon: "✅" },
    { word: "Update the contract", phonetic: "/ˈʌpdeɪt ðə ˈkɒntrækt/", definition: "Cập nhật hợp đồng", icon: "📄" },
    { word: "Check the balance", phonetic: "/tʃek ðə ˈbæləns/", definition: "Kiểm tra số dư công nợ", icon: "💰" },
    { word: "Reply to your email", phonetic: "/rɪˈplaɪ tə jɔːr ˈiːmeɪl/", definition: "Trả lời thư của quý khách", icon: "📧" },
    { word: "Process the payment", phonetic: "/ˈprəʊses ðə ˈpeɪmənt/", definition: "Xử lý thanh toán", icon: "💳" },
    { word: "Book the meeting room", phonetic: "/bʊk ðə ˈmiːtɪŋ ruːm/", definition: "Giữ phòng họp", icon: "📅" },
    { word: "Call the supplier", phonetic: "/kɔːl ðə səˈplaɪə/", definition: "Gọi cho nhà cung cấp", icon: "☎️" },
    { word: "Sign the agreement", phonetic: "/saɪn ði əˈɡriːmənt/", definition: "Ký thỏa thuận", icon: "✍️" },
    { word: "Email the price list", phonetic: "/ˈiːmeɪl ðə praɪs lɪst/", definition: "Gửi bảng giá qua thư", icon: "🏷️" },
    { word: "Release the rooms", phonetic: "/rɪˈliːs ðə ruːmz/", definition: "Trả lại số phòng chưa bán", icon: "🔓" },
  ],
  partners: [
    { word: "Reservations team", phonetic: "/ˌrezəˈveɪʃnz tiːm/", definition: "Bộ phận đặt phòng", icon: "📞" },
    { word: "Accounting team", phonetic: "/əˈkaʊntɪŋ tiːm/", definition: "Bộ phận kế toán", icon: "🧮" },
    { word: "Finance team", phonetic: "/ˈfaɪnæns tiːm/", definition: "Bộ phận tài chính", icon: "💰" },
    { word: "Sales team", phonetic: "/seɪlz tiːm/", definition: "Bộ phận kinh doanh", icon: "📣" },
    { word: "Revenue team", phonetic: "/ˈrevənjuː tiːm/", definition: "Bộ phận quản lý doanh thu", icon: "📈" },
    { word: "Front office", phonetic: "/frʌnt ˈɒfɪs/", definition: "Bộ phận tiền sảnh", icon: "🛎️" },
    { word: "Personnel team", phonetic: "/ˌpɜːsəˈnel tiːm/", definition: "Bộ phận nhân sự", icon: "🧑‍💼" },
    { word: "Purchasing team", phonetic: "/ˈpɜːtʃəsɪŋ tiːm/", definition: "Bộ phận thu mua", icon: "🛒" },
    { word: "Credit control team", phonetic: "/ˈkredɪt kənˈtrəʊl tiːm/", definition: "Bộ phận quản lý công nợ", icon: "💳" },
    { word: "Payroll office", phonetic: "/ˈpeɪrəʊl ˈɒfɪs/", definition: "Bộ phận tính lương", icon: "💵" },
    { word: "Head office", phonetic: "/hed ˈɒfɪs/", definition: "Trụ sở chính", icon: "🏢" },
    { word: "Banqueting team", phonetic: "/ˈbæŋkwɪtɪŋ tiːm/", definition: "Bộ phận tiệc", icon: "🍽️" },
  ],
  complaints: [
    { word: "Late invoice", phonetic: "/leɪt ˈɪnvɔɪs/", definition: "Hóa đơn gửi trễ", icon: "⏰" },
    { word: "Wrong billing amount", phonetic: "/rɒŋ ˈbɪlɪŋ əˈmaʊnt/", definition: "Số tiền xuất hóa đơn sai", icon: "💸" },
    { word: "Unanswered quotation", phonetic: "/ʌnˈɑːnsəd kwəʊˈteɪʃn/", definition: "Báo giá chưa được trả lời", icon: "📭" },
    { word: "Rate discrepancy", phonetic: "/reɪt dɪsˈkrepənsi/", definition: "Chênh lệch giá", icon: "⚖️" },
    { word: "Double charge", phonetic: "/ˈdʌbl tʃɑːdʒ/", definition: "Bị tính tiền hai lần", icon: "💳" },
    { word: "Missing purchase order", phonetic: "/ˈmɪsɪŋ ˈpɜːtʃəs ˈɔːdə/", definition: "Thiếu đơn đặt mua", icon: "📄" },
    { word: "Overdue payment", phonetic: "/ˌəʊvəˈdjuː ˈpeɪmənt/", definition: "Khoản thanh toán quá hạn", icon: "🔔" },
    { word: "Wrong company name", phonetic: "/rɒŋ ˈkʌmpəni neɪm/", definition: "Sai tên công ty", icon: "🏢" },
    { word: "Delayed refund", phonetic: "/dɪˈleɪd ˈriːfʌnd/", definition: "Hoàn tiền chậm", icon: "🔁" },
    { word: "Tax code error", phonetic: "/tæks kəʊd ˈerə/", definition: "Sai mã số thuế", icon: "🧾" },
    { word: "Missing signature", phonetic: "/ˈmɪsɪŋ ˈsɪɡnətʃə/", definition: "Thiếu chữ ký", icon: "✍️" },
    { word: "Unpaid balance", phonetic: "/ʌnˈpeɪd ˈbæləns/", definition: "Số dư chưa thanh toán", icon: "📉" },
  ],
  solutions: [
    { word: "Issue a credit note", phonetic: "/ˈɪʃuː ə ˈkredɪt nəʊt/", definition: "Phát hành giấy báo có", icon: "🧾" },
    { word: "Revise the quotation", phonetic: "/rɪˈvaɪz ðə kwəʊˈteɪʃn/", definition: "Sửa lại báo giá", icon: "✏️" },
    { word: "Extend the deadline", phonetic: "/ɪkˈstend ðə ˈdedlaɪn/", definition: "Gia hạn thời hạn", icon: "⏳" },
    { word: "Cancel the charge", phonetic: "/ˈkænsl ðə tʃɑːdʒ/", definition: "Hủy khoản thu", icon: "❌" },
    { word: "Split the invoice", phonetic: "/splɪt ði ˈɪnvɔɪs/", definition: "Tách hóa đơn", icon: "✂️" },
    { word: "Resend the contract", phonetic: "/ˌriːˈsend ðə ˈkɒntrækt/", definition: "Gửi lại hợp đồng", icon: "📤" },
    { word: "Correct the tax code", phonetic: "/kəˈrekt ðə tæks kəʊd/", definition: "Sửa mã số thuế", icon: "🔢" },
    { word: "Apply a discount", phonetic: "/əˈplaɪ ə ˈdɪskaʊnt/", definition: "Áp dụng chiết khấu", icon: "🏷️" },
    { word: "Refund the deposit", phonetic: "/ˈriːfʌnd ðə dɪˈpɒzɪt/", definition: "Hoàn lại tiền cọc", icon: "💰" },
    { word: "Change the payment date", phonetic: "/tʃeɪndʒ ðə ˈpeɪmənt deɪt/", definition: "Đổi ngày thanh toán", icon: "📅" },
    { word: "Hold the booking", phonetic: "/həʊld ðə ˈbʊkɪŋ/", definition: "Giữ chỗ tạm thời", icon: "⏸️" },
    { word: "Send a new invoice", phonetic: "/send ə njuː ˈɪnvɔɪs/", definition: "Gửi hóa đơn mới", icon: "📨" },
  ],
  handover: [
    { word: "Pending quotation", phonetic: "/ˈpendɪŋ kwəʊˈteɪʃn/", definition: "Báo giá đang chờ", icon: "📋" },
    { word: "Outstanding balance", phonetic: "/aʊtˈstændɪŋ ˈbæləns/", definition: "Số dư còn phải thu", icon: "💰" },
    { word: "Contract renewal date", phonetic: "/ˈkɒntrækt rɪˈnjuːəl deɪt/", definition: "Ngày gia hạn hợp đồng", icon: "📆" },
    { word: "Payment tracker", phonetic: "/ˈpeɪmənt ˈtrækə/", definition: "Bảng theo dõi thanh toán", icon: "📊" },
    { word: "Group booking list", phonetic: "/ɡruːp ˈbʊkɪŋ lɪst/", definition: "Danh sách đặt đoàn", icon: "👥" },
    { word: "Invoice folder", phonetic: "/ˈɪnvɔɪs ˈfəʊldə/", definition: "Cặp hồ sơ hóa đơn", icon: "🗂️" },
    { word: "Petty cash box", phonetic: "/ˈpeti kæʃ bɒks/", definition: "Quỹ tiền mặt nhỏ", icon: "💵" },
    { word: "Client call log", phonetic: "/ˈklaɪənt kɔːl lɒɡ/", definition: "Sổ ghi cuộc gọi khách hàng", icon: "☎️" },
    { word: "Unsigned contract", phonetic: "/ʌnˈsaɪnd ˈkɒntrækt/", definition: "Hợp đồng chưa ký", icon: "✍️" },
    { word: "Daily revenue report", phonetic: "/ˈdeɪli ˈrevənjuː rɪˈpɔːt/", definition: "Báo cáo doanh thu ngày", icon: "📈" },
    { word: "Supplier payment list", phonetic: "/səˈplaɪə ˈpeɪmənt lɪst/", definition: "Danh sách thanh toán nhà cung cấp", icon: "🏭" },
    { word: "Stationery order", phonetic: "/ˈsteɪʃənri ˈɔːdə/", definition: "Đơn đặt văn phòng phẩm", icon: "✏️" },
  ],
  wrapUp: [
    { word: "Final quotation", phonetic: "/ˈfaɪnl kwəʊˈteɪʃn/", definition: "Báo giá cuối cùng", icon: "📄" },
    { word: "Total amount", phonetic: "/ˈtəʊtl əˈmaʊnt/", definition: "Tổng số tiền", icon: "💵" },
    { word: "Due date", phonetic: "/djuː deɪt/", definition: "Ngày đến hạn", icon: "📅" },
    { word: "Invoice number", phonetic: "/ˈɪnvɔɪs ˈnʌmbə/", definition: "Số hóa đơn", icon: "🧾" },
    { word: "Room block", phonetic: "/ruːm blɒk/", definition: "Số phòng giữ cho đoàn", icon: "🏨" },
    { word: "Agreed rate", phonetic: "/əˈɡriːd reɪt/", definition: "Mức giá đã thống nhất", icon: "🤝" },
    { word: "Advance deposit", phonetic: "/ədˈvɑːns dɪˈpɒzɪt/", definition: "Tiền đặt cọc trước", icon: "💰" },
    { word: "Delivery address", phonetic: "/dɪˈlɪvəri əˈdres/", definition: "Địa chỉ giao hàng", icon: "📍" },
    { word: "Bank account number", phonetic: "/bæŋk əˈkaʊnt ˈnʌmbə/", definition: "Số tài khoản ngân hàng", icon: "🏦" },
    { word: "Cancellation deadline", phonetic: "/ˌkænsəˈleɪʃn ˈdedlaɪn/", definition: "Hạn chót hủy", icon: "⏳" },
    { word: "Event headcount", phonetic: "/ɪˈvent ˈhedkaʊnt/", definition: "Số khách dự sự kiện", icon: "👥" },
    { word: "Company tax code", phonetic: "/ˈkʌmpəni tæks kəʊd/", definition: "Mã số thuế công ty", icon: "🏢" },
  ],
};

export const P3_BANKS: Record<string, P3Bank> = {
  FO: FO_BANK,
  FB: FB_BANK,
  HK: HK_BANK,
  SW: SW_BANK,
  GR: GR_BANK,
  BO: BO_BANK,
};
