// ============================================================
// PHASE 2 word banks — A2.1 (weeks 15-22).
//
// Phase 1 ran at ~70% department-specific. Phase 2 pushes further:
// from here the *topics* separate completely and only the language
// FUNCTION stays shared (a service sequence, an offer, a rule, a past
// report). So the banks carry ~10 of each week's ~13 headwords.
//
// One bank per week 15-21 (10 words each) + an 8-word `wrapUp` bank for
// the week-22 checkpoint = 78 department-specific headwords each.
//
// Enforced by scripts/verify-content.ts:
//  · No word may repeat another headword the same department already
//    met in Phase 0 or Phase 1 (intra-department duplication gate).
//  · >=75% of each week's headwords must be department-specific.
//  · Sentences built from these words stay within the 12-word A2.1 cap.
// ============================================================

export type P2Word = { word: string; phonetic: string; definition: string; icon: string };

export type P2Bank = {
  /** W15 — the named steps of this department's core service sequence. */
  steps: P2Word[];
  /** W16 — what this department offers guests. */
  offers: P2Word[];
  /** W17 — guest details this department asks for and confirms. */
  details: P2Word[];
  /** W18 — paperwork and payment items it handles. */
  paperwork: P2Word[];
  /** W19 — house rules and safety items it must state. */
  rules: P2Word[];
  /** W20 — the options it presents when a guest must choose. */
  choices: P2Word[];
  /** W21 — vocabulary for reporting completed work in the past tense. */
  reports: P2Word[];
  /** W22 — checkpoint wrap-up words. */
  wrapUp: P2Word[];
};

const FO_BANK: P2Bank = {
  steps: [
    { word: "Greet the guest", phonetic: "/ɡriːt ðə ɡest/", definition: "Chào đón khách", icon: "🛬" },
    { word: "Check the profile", phonetic: "/tʃek ðə ˈprəʊfaɪl/", definition: "Kiểm tra hồ sơ khách", icon: "📇" },
    { word: "Allocate the room", phonetic: "/ˈæləkeɪt ðə ruːm/", definition: "Phân phòng", icon: "🗂️" },
    { word: "Offer a welcome drink", phonetic: "/ˈɒfə ə ˈwelkəm drɪŋk/", definition: "Mời nước chào mừng", icon: "🥤" },
    { word: "Escort the guest", phonetic: "/ɪˈskɔːt ðə ɡest/", definition: "Dẫn khách lên phòng", icon: "🚶" },
    { word: "Show the room", phonetic: "/ʃəʊ ðə ruːm/", definition: "Giới thiệu phòng", icon: "🔎" },
    { word: "Follow the steps", phonetic: "/ˈfɒləʊ ðə steps/", definition: "Làm theo các bước", icon: "🪜" },
    { word: "Confirm the details", phonetic: "/kənˈfɜːm ðə ˈdiːteɪlz/", definition: "Xác nhận thông tin", icon: "🔢" },
    { word: "Handover", phonetic: "/ˈhændəʊvə/", definition: "Bàn giao", icon: "🤝" },
    { word: "Checklist item", phonetic: "/ˈtʃeklɪst ˈaɪtəm/", definition: "Mục trong bảng kiểm", icon: "☑️" },
  ],
  offers: [
    { word: "Upgrade", phonetic: "/ˈʌpɡreɪd/", definition: "Nâng hạng phòng", icon: "⬆️" },
    { word: "Higher floor", phonetic: "/ˈhaɪə flɔː/", definition: "Tầng cao hơn", icon: "🏢" },
    { word: "Sea view", phonetic: "/siː vjuː/", definition: "Hướng nhìn ra biển", icon: "🌊" },
    { word: "Connecting room", phonetic: "/kəˈnektɪŋ ruːm/", definition: "Phòng thông nhau", icon: "🚪" },
    { word: "Airport pick-up", phonetic: "/ˈeəpɔːt ˈpɪk ʌp/", definition: "Đón sân bay", icon: "🚐" },
    { word: "Baggage storage", phonetic: "/ˈbæɡɪdʒ ˈstɔːrɪdʒ/", definition: "Gửi hành lý", icon: "🧳" },
    { word: "Newspaper delivery", phonetic: "/ˈnjuːzpeɪpə dɪˈlɪvəri/", definition: "Giao báo tận phòng", icon: "📰" },
    { word: "Free of charge", phonetic: "/friː əv tʃɑːdʒ/", definition: "Miễn phí", icon: "🆓" },
    { word: "Optional", phonetic: "/ˈɒpʃənl/", definition: "Tùy chọn, không bắt buộc", icon: "🔘" },
    { word: "Include", phonetic: "/ɪnˈkluːd/", definition: "Bao gồm", icon: "➕" },
  ],
  details: [
    { word: "Full name", phonetic: "/fʊl neɪm/", definition: "Họ tên đầy đủ", icon: "🪪" },
    { word: "Nationality", phonetic: "/ˌnæʃəˈnæləti/", definition: "Quốc tịch", icon: "🌏" },
    { word: "Date of birth", phonetic: "/deɪt əv bɜːθ/", definition: "Ngày sinh", icon: "🎂" },
    { word: "Contact number", phonetic: "/ˈkɒntækt ˈnʌmbə/", definition: "Số liên lạc", icon: "📱" },
    { word: "Length of stay", phonetic: "/leŋθ əv steɪ/", definition: "Số đêm lưu trú", icon: "🌙" },
    { word: "Spelling", phonetic: "/ˈspelɪŋ/", definition: "Cách viết chính tả", icon: "🔤" },
    { word: "Home address", phonetic: "/həʊm əˈdres/", definition: "Địa chỉ nhà", icon: "✏️" },
    { word: "Passport number", phonetic: "/ˈpɑːspɔːt ˈnʌmbə/", definition: "Số hộ chiếu", icon: "🔍" },
    { word: "Arrival time", phonetic: "/əˈraɪvl taɪm/", definition: "Giờ đến", icon: "🎯" },
    { word: "Detail", phonetic: "/ˈdiːteɪl/", definition: "Chi tiết thông tin", icon: "📋" },
  ],
  paperwork: [
    { word: "Registration card", phonetic: "/ˌredʒɪˈstreɪʃn kɑːd/", definition: "Phiếu đăng ký lưu trú", icon: "📝" },
    { word: "Invoice address", phonetic: "/ˈɪnvɔɪs əˈdres/", definition: "Địa chỉ xuất hóa đơn", icon: "🏠" },
    { word: "Company name", phonetic: "/ˈkʌmpəni neɪm/", definition: "Tên công ty", icon: "🏢" },
    { word: "Tax code", phonetic: "/tæks kəʊd/", definition: "Mã số thuế", icon: "🔢" },
    { word: "Service charge", phonetic: "/ˈsɜːvɪs tʃɑːdʒ/", definition: "Phí phục vụ", icon: "💼" },
    { word: "Currency", phonetic: "/ˈkʌrənsi/", definition: "Loại tiền tệ", icon: "💱" },
    { word: "Exchange rate", phonetic: "/ɪksˈtʃeɪndʒ reɪt/", definition: "Tỷ giá", icon: "📈" },
    { word: "Settle the bill", phonetic: "/ˈsetl ðə bɪl/", definition: "Thanh toán hóa đơn", icon: "✅" },
    { word: "Processing", phonetic: "/ˈprəʊsesɪŋ/", definition: "Đang xử lý", icon: "⏳" },
    { word: "Copy", phonetic: "/ˈkɒpi/", definition: "Bản sao", icon: "🖨️" },
  ],
  rules: [
    { word: "Quiet hours", phonetic: "/ˈkwaɪət ˈaʊəz/", definition: "Giờ giữ yên tĩnh", icon: "🤫" },
    { word: "Visitor policy", phonetic: "/ˈvɪzɪtə ˈpɒləsi/", definition: "Quy định khách thăm", icon: "👥" },
    { word: "Smoking area", phonetic: "/ˈsməʊkɪŋ ˈeəriə/", definition: "Khu vực hút thuốc", icon: "🚬" },
    { word: "Emergency exit", phonetic: "/ɪˈmɜːdʒənsi ˈeksɪt/", definition: "Lối thoát hiểm", icon: "🚨" },
    { word: "Fire alarm", phonetic: "/ˈfaɪə əˈlɑːm/", definition: "Chuông báo cháy", icon: "🔔" },
    { word: "Valuables", phonetic: "/ˈvæljuəblz/", definition: "Đồ có giá trị", icon: "💎" },
    { word: "Safety box", phonetic: "/ˈseɪfti bɒks/", definition: "Két an toàn", icon: "🔐" },
    { word: "Not allowed", phonetic: "/nɒt əˈlaʊd/", definition: "Không được phép", icon: "🚫" },
    { word: "Remind", phonetic: "/rɪˈmaɪnd/", definition: "Nhắc nhở", icon: "📢" },
    { word: "Regulation", phonetic: "/ˌreɡjuˈleɪʃn/", definition: "Quy định", icon: "📜" },
  ],
  choices: [
    { word: "Twin bed", phonetic: "/twɪn bed/", definition: "Hai giường đơn", icon: "🛏️" },
    { word: "Double bed", phonetic: "/ˈdʌbl bed/", definition: "Giường đôi", icon: "🛌" },
    { word: "City view", phonetic: "/ˈsɪti vjuː/", definition: "Hướng nhìn thành phố", icon: "🌆" },
    { word: "Non-smoking room", phonetic: "/nɒn ˈsməʊkɪŋ ruːm/", definition: "Phòng không hút thuốc", icon: "🚭" },
    { word: "Corner room", phonetic: "/ˈkɔːnə ruːm/", definition: "Phòng góc", icon: "❤️" },
    { word: "Quiet room", phonetic: "/ˈkwaɪət ruːm/", definition: "Phòng yên tĩnh", icon: "🔄" },
    { word: "Either one", phonetic: "/ˈaɪðə wʌn/", definition: "Cái nào cũng được", icon: "🤷" },
    { word: "Best option", phonetic: "/best ˈɒpʃn/", definition: "Phương án tốt nhất", icon: "👍" },
    { word: "Ground floor", phonetic: "/ɡraʊnd flɔː/", definition: "Tầng trệt", icon: "🔇" },
    { word: "Option", phonetic: "/ˈɒpʃn/", definition: "Lựa chọn", icon: "🔀" },
  ],
  reports: [
    { word: "Arrived", phonetic: "/əˈraɪvd/", definition: "Đã đến", icon: "🛬" },
    { word: "Checked in", phonetic: "/tʃekt ɪn/", definition: "Đã nhận phòng", icon: "📥" },
    { word: "Called", phonetic: "/kɔːld/", definition: "Đã gọi", icon: "📞" },
    { word: "Informed", phonetic: "/ɪnˈfɔːmd/", definition: "Đã báo cho biết", icon: "📢" },
    { word: "Yesterday", phonetic: "/ˈjestədeɪ/", definition: "Hôm qua", icon: "📅" },
    { word: "Last night", phonetic: "/lɑːst naɪt/", definition: "Đêm qua", icon: "🌙" },
    { word: "Shift report", phonetic: "/ʃɪft rɪˈpɔːt/", definition: "Báo cáo ca", icon: "📄" },
    { word: "Solved", phonetic: "/sɒlvd/", definition: "Đã giải quyết", icon: "✅" },
    { word: "Passed on", phonetic: "/pɑːst ɒn/", definition: "Đã chuyển tiếp", icon: "➡️" },
    { word: "Noted", phonetic: "/ˈnəʊtɪd/", definition: "Đã ghi nhận", icon: "🗒️" },
  ],
  wrapUp: [
    { word: "Smooth", phonetic: "/smuːð/", definition: "Trôi chảy, suôn sẻ", icon: "🌊" },
    { word: "On time", phonetic: "/ɒn taɪm/", definition: "Đúng giờ", icon: "⏰" },
    { word: "Service level", phonetic: "/ˈsɜːvɪs ˈlevl/", definition: "Mức độ phục vụ", icon: "📏" },
    { word: "Improve", phonetic: "/ɪmˈpruːv/", definition: "Cải thiện", icon: "📈" },
    { word: "Guest comment", phonetic: "/ɡest ˈkɒment/", definition: "Nhận xét của khách", icon: "💬" },
    { word: "Well handled", phonetic: "/wel ˈhændld/", definition: "Xử lý tốt", icon: "👏" },
    { word: "Next shift", phonetic: "/nekst ʃɪft/", definition: "Ca kế tiếp", icon: "🔁" },
    { word: "Recap", phonetic: "/ˈriːkæp/", definition: "Tóm tắt lại", icon: "📋" },
    { word: "Log book", phonetic: "/lɒɡ bʊk/", definition: "Sổ nhật ký ca", icon: "📓" },
    { word: "Guest satisfied", phonetic: "/ɡest ˈsætɪsfaɪd/", definition: "Khách hài lòng", icon: "😊" },
  ],
};

const FB_BANK: P2Bank = {
  steps: [
    { word: "Seat the guest", phonetic: "/siːt ðə ɡest/", definition: "Xếp chỗ cho khách", icon: "🪑" },
    { word: "Present the menu", phonetic: "/prɪˈzent ðə ˈmenjuː/", definition: "Đưa thực đơn", icon: "📖" },
    { word: "Take the order", phonetic: "/teɪk ði ˈɔːdə/", definition: "Ghi món", icon: "📝" },
    { word: "Repeat the order", phonetic: "/rɪˈpiːt ði ˈɔːdə/", definition: "Nhắc lại món đã gọi", icon: "🔁" },
    { word: "Send to kitchen", phonetic: "/send tə ˈkɪtʃɪn/", definition: "Chuyển bếp", icon: "🍳" },
    { word: "Serve the starter", phonetic: "/sɜːv ðə ˈstɑːtə/", definition: "Phục vụ món khai vị", icon: "🥗" },
    { word: "Clear the plates", phonetic: "/klɪə ðə pleɪts/", definition: "Dọn đĩa", icon: "🍽️" },
    { word: "Offer dessert", phonetic: "/ˈɒfə dɪˈzɜːt/", definition: "Mời món tráng miệng", icon: "🍰" },
    { word: "Sequence", phonetic: "/ˈsiːkwəns/", definition: "Trình tự", icon: "🔢" },
    { word: "Course", phonetic: "/kɔːs/", definition: "Món trong bữa", icon: "🍲" },
  ],
  offers: [
    { word: "Starter", phonetic: "/ˈstɑːtə/", definition: "Món khai vị", icon: "🥗" },
    { word: "Main course", phonetic: "/meɪn kɔːs/", definition: "Món chính", icon: "🍛" },
    { word: "Side dish", phonetic: "/saɪd dɪʃ/", definition: "Món ăn kèm", icon: "🥔" },
    { word: "Soft drink", phonetic: "/sɒft drɪŋk/", definition: "Nước ngọt", icon: "🥤" },
    { word: "Fresh juice", phonetic: "/freʃ dʒuːs/", definition: "Nước ép tươi", icon: "🍊" },
    { word: "Set lunch", phonetic: "/set lʌntʃ/", definition: "Suất trưa cố định", icon: "🍱" },
    { word: "Today's special", phonetic: "/təˈdeɪz ˈspeʃl/", definition: "Món đặc biệt hôm nay", icon: "⭐" },
    { word: "Second helping", phonetic: "/ˈsekənd ˈhelpɪŋ/", definition: "Phần thứ hai", icon: "➕" },
    { word: "Complimentary bread", phonetic: "/ˌkɒmplɪˈmentri bred/", definition: "Bánh mì tặng kèm", icon: "🍞" },
    { word: "Try", phonetic: "/traɪ/", definition: "Thử", icon: "😋" },
  ],
  details: [
    { word: "Table number", phonetic: "/ˈteɪbl ˈnʌmbə/", definition: "Số bàn", icon: "🔢" },
    { word: "Number of guests", phonetic: "/ˈnʌmbə əv ɡests/", definition: "Số lượng khách", icon: "👥" },
    { word: "Dietary need", phonetic: "/ˈdaɪətəri niːd/", definition: "Nhu cầu ăn kiêng", icon: "🥦" },
    { word: "Meat preference", phonetic: "/miːt ˈprefrəns/", definition: "Loại thịt ưa dùng", icon: "🚫" },
    { word: "Nut allergy", phonetic: "/nʌt ˈælədʒi/", definition: "Dị ứng hạt", icon: "🥜" },
    { word: "Sugar level", phonetic: "/ˈʃʊɡə ˈlevl/", definition: "Mức đường", icon: "🍬" },
    { word: "Cooking level", phonetic: "/ˈkʊkɪŋ ˈlevl/", definition: "Mức độ chín", icon: "🥩" },
    { word: "Order detail", phonetic: "/ˈɔːdə ˈdiːteɪl/", definition: "Chi tiết món gọi", icon: "✅" },
    { word: "Drink choice", phonetic: "/drɪŋk tʃɔɪs/", definition: "Lựa chọn đồ uống", icon: "🥂" },
    { word: "Final order", phonetic: "/ˈfaɪnl ˈɔːdə/", definition: "Đơn gọi cuối cùng", icon: "🏁" },
  ],
  paperwork: [
    { word: "Order slip", phonetic: "/ˈɔːdə slɪp/", definition: "Phiếu gọi món", icon: "🧾" },
    { word: "Split the bill", phonetic: "/splɪt ðə bɪl/", definition: "Tách hóa đơn", icon: "✂️" },
    { word: "Charge to room", phonetic: "/tʃɑːdʒ tə ruːm/", definition: "Tính vào phòng", icon: "🏨" },
    { word: "Sign here", phonetic: "/saɪn hɪə/", definition: "Ký vào đây", icon: "✍️" },
    { word: "VAT", phonetic: "/ˌviː eɪ ˈtiː/", definition: "Thuế giá trị gia tăng", icon: "🧮" },
    { word: "Discount", phonetic: "/ˈdɪskaʊnt/", definition: "Giảm giá", icon: "🏷️" },
    { word: "Member card", phonetic: "/ˈmembə kɑːd/", definition: "Thẻ thành viên", icon: "💳" },
    { word: "Voucher", phonetic: "/ˈvaʊtʃə/", definition: "Phiếu ưu đãi", icon: "🎟️" },
    { word: "Amount", phonetic: "/əˈmaʊnt/", definition: "Số tiền", icon: "💰" },
    { word: "Print the bill", phonetic: "/prɪnt ðə bɪl/", definition: "In hóa đơn", icon: "🖨️" },
  ],
  rules: [
    { word: "Dress code", phonetic: "/dres kəʊd/", definition: "Quy định trang phục", icon: "👔" },
    { word: "Hot plate", phonetic: "/hɒt pleɪt/", definition: "Đĩa nóng", icon: "🔥" },
    { word: "Wet floor", phonetic: "/wet flɔː/", definition: "Sàn ướt", icon: "⚠️" },
    { word: "Raw food", phonetic: "/rɔː fuːd/", definition: "Thức ăn sống", icon: "🍣" },
    { word: "Food safety", phonetic: "/fuːd ˈseɪfti/", definition: "An toàn thực phẩm", icon: "🛡️" },
    { word: "Wash hands", phonetic: "/wɒʃ hændz/", definition: "Rửa tay", icon: "🧼" },
    { word: "Buffet rule", phonetic: "/ˈbʊfeɪ ruːl/", definition: "Nội quy buffet", icon: "📜" },
    { word: "Take away food", phonetic: "/teɪk əˈweɪ fuːd/", definition: "Mang thức ăn ra ngoài", icon: "🥡" },
    { word: "Careful", phonetic: "/ˈkeəfl/", definition: "Cẩn thận", icon: "❗" },
    { word: "Allowed", phonetic: "/əˈlaʊd/", definition: "Được phép", icon: "✔️" },
  ],
  choices: [
    { word: "Chicken or beef", phonetic: "/ˈtʃɪkɪn ɔː biːf/", definition: "Gà hay bò", icon: "🍗" },
    { word: "Rice or noodles", phonetic: "/raɪs ɔː ˈnuːdlz/", definition: "Cơm hay mì", icon: "🍜" },
    { word: "Still or sparkling", phonetic: "/stɪl ɔː ˈspɑːklɪŋ/", definition: "Nước thường hay có ga", icon: "💧" },
    { word: "Indoor or outdoor", phonetic: "/ˈɪndɔː ɔː ˈaʊtdɔː/", definition: "Trong nhà hay ngoài trời", icon: "🌤️" },
    { word: "Mild flavour", phonetic: "/maɪld ˈfleɪvə/", definition: "Vị nhẹ", icon: "🌱" },
    { word: "Popular dish", phonetic: "/ˈpɒpjələ dɪʃ/", definition: "Món được ưa chuộng", icon: "🌟" },
    { word: "Light meal", phonetic: "/laɪt miːl/", definition: "Bữa nhẹ", icon: "🥗" },
    { word: "Sharing plate", phonetic: "/ˈʃeərɪŋ pleɪt/", definition: "Món dùng chung", icon: "🍲" },
    { word: "Chef suggestion", phonetic: "/ʃef səˈdʒestʃən/", definition: "Gợi ý của bếp trưởng", icon: "💡" },
    { word: "Favourite", phonetic: "/ˈfeɪvərɪt/", definition: "Món ưa thích", icon: "❤️" },
  ],
  reports: [
    { word: "Served", phonetic: "/sɜːvd/", definition: "Đã phục vụ", icon: "🍽️" },
    { word: "Ordered", phonetic: "/ˈɔːdəd/", definition: "Đã gọi món", icon: "📝" },
    { word: "Prepared", phonetic: "/prɪˈpeəd/", definition: "Đã chuẩn bị", icon: "⚙️" },
    { word: "Ran out", phonetic: "/ræn aʊt/", definition: "Đã hết", icon: "📭" },
    { word: "Last night", phonetic: "/lɑːst naɪt/", definition: "Tối qua", icon: "🌙" },
    { word: "Busy period", phonetic: "/ˈbɪzi ˈpɪəriəd/", definition: "Giờ cao điểm", icon: "🏃" },
    { word: "Covers", phonetic: "/ˈkʌvəz/", definition: "Lượt khách phục vụ", icon: "🔢" },
    { word: "Returned", phonetic: "/rɪˈtɜːnd/", definition: "Đã trả lại", icon: "↩️" },
    { word: "Replaced", phonetic: "/rɪˈpleɪst/", definition: "Đã đổi cái khác", icon: "🔄" },
    { word: "Closed the shift", phonetic: "/kləʊzd ðə ʃɪft/", definition: "Đã đóng ca", icon: "🔒" },
  ],
  wrapUp: [
    { word: "Full house", phonetic: "/fʊl haʊs/", definition: "Kín bàn", icon: "🈵" },
    { word: "Teamwork", phonetic: "/ˈtiːmwɜːk/", definition: "Làm việc nhóm", icon: "🤝" },
    { word: "Praise", phonetic: "/preɪz/", definition: "Lời khen ngợi", icon: "👏" },
    { word: "Smooth service", phonetic: "/smuːð ˈsɜːvɪs/", definition: "Phục vụ trôi chảy", icon: "🌊" },
    { word: "Stock", phonetic: "/stɒk/", definition: "Hàng tồn", icon: "📦" },
    { word: "Set up again", phonetic: "/set ʌp əˈɡen/", definition: "Bày lại", icon: "🔁" },
    { word: "Menu update", phonetic: "/ˈmenjuː ʌpˈdeɪt/", definition: "Cập nhật thực đơn", icon: "📋" },
    { word: "Guest count", phonetic: "/ɡest kaʊnt/", definition: "Số khách", icon: "🔢" },
    { word: "Clean station", phonetic: "/kliːn ˈsteɪʃn/", definition: "Quầy đã dọn sạch", icon: "✨" },
    { word: "Shift end", phonetic: "/ʃɪft end/", definition: "Kết thúc ca", icon: "🏁" },
  ],
};

const HK_BANK: P2Bank = {
  steps: [
    { word: "Enter the room", phonetic: "/ˈentə ðə ruːm/", definition: "Vào phòng", icon: "🚪" },
    { word: "Open the curtains", phonetic: "/ˈəʊpən ðə ˈkɜːtnz/", definition: "Mở rèm", icon: "🪟" },
    { word: "Strip the bed", phonetic: "/strɪp ðə bed/", definition: "Tháo ga giường", icon: "🛏️" },
    { word: "Wipe the surfaces", phonetic: "/waɪp ðə ˈsɜːfɪsɪz/", definition: "Lau bề mặt", icon: "🧽" },
    { word: "Restock", phonetic: "/ˌriːˈstɒk/", definition: "Bổ sung vật dụng", icon: "🧴" },
    { word: "Check everything", phonetic: "/tʃek ˈevriθɪŋ/", definition: "Kiểm tra toàn bộ", icon: "🔍" },
    { word: "Close the door", phonetic: "/kləʊz ðə dɔː/", definition: "Đóng cửa", icon: "🚪" },
    { word: "Update the status", phonetic: "/ʌpˈdeɪt ðə ˈsteɪtəs/", definition: "Cập nhật trạng thái phòng", icon: "🚦" },
    { word: "Room routine", phonetic: "/ruːm ruːˈtiːn/", definition: "Quy trình phòng", icon: "🪜" },
    { word: "Priority", phonetic: "/praɪˈɒrəti/", definition: "Ưu tiên", icon: "❗" },
  ],
  offers: [
    { word: "Turndown service", phonetic: "/ˈtɜːndaʊn ˈsɜːvɪs/", definition: "Dịch vụ chỉnh giường buổi tối", icon: "🌙" },
    { word: "Baby cot", phonetic: "/ˈbeɪbi kɒt/", definition: "Nôi em bé", icon: "🍼" },
    { word: "Extra hanger", phonetic: "/ˈekstrə ˈhæŋə/", definition: "Móc treo thêm", icon: "🧥" },
    { word: "Shoe polish", phonetic: "/ʃuː ˈpɒlɪʃ/", definition: "Xi đánh giày", icon: "👞" },
    { word: "Sewing kit", phonetic: "/ˈsəʊɪŋ kɪt/", definition: "Bộ kim chỉ", icon: "🧵" },
    { word: "Pillow menu", phonetic: "/ˈpɪləʊ ˈmenjuː/", definition: "Danh mục gối", icon: "🛌" },
    { word: "Air freshener", phonetic: "/eə ˈfreʃnə/", definition: "Xịt thơm phòng", icon: "🌸" },
    { word: "Bath robe", phonetic: "/bɑːθ rəʊb/", definition: "Áo choàng tắm", icon: "🥼" },
    { word: "Provide", phonetic: "/prəˈvaɪd/", definition: "Cung cấp", icon: "🎁" },
    { word: "At no cost", phonetic: "/ət nəʊ kɒst/", definition: "Không mất phí", icon: "🆓" },
  ],
  details: [
    { word: "Cleaning time", phonetic: "/ˈkliːnɪŋ taɪm/", definition: "Giờ dọn phòng", icon: "🕐" },
    { word: "Preferred time", phonetic: "/prɪˈfɜːd taɪm/", definition: "Giờ khách muốn", icon: "⏰" },
    { word: "Number of nights", phonetic: "/ˈnʌmbə əv naɪts/", definition: "Số đêm lưu trú", icon: "🌙" },
    { word: "Dust allergy", phonetic: "/dʌst ˈælədʒi/", definition: "Dị ứng bụi", icon: "🤧" },
    { word: "Pillow firmness", phonetic: "/ˈpɪləʊ ˈfɜːmnəs/", definition: "Độ cứng của gối", icon: "🛏️" },
    { word: "Room note", phonetic: "/ruːm nəʊt/", definition: "Ghi chú phòng", icon: "❓" },
    { word: "Service note", phonetic: "/ˈsɜːvɪs nəʊt/", definition: "Ghi chú dịch vụ", icon: "✅" },
    { word: "Special note", phonetic: "/ˈspeʃl nəʊt/", definition: "Ghi chú đặc biệt", icon: "🗒️" },
    { word: "Guest instruction", phonetic: "/ɡest ɪnˈstrʌkʃn/", definition: "Dặn dò của khách", icon: "💡" },
    { word: "Cleaning note", phonetic: "/ˈkliːnɪŋ nəʊt/", definition: "Ghi chú dọn phòng", icon: "✏️" },
  ],
  paperwork: [
    { word: "Room list", phonetic: "/ruːm lɪst/", definition: "Danh sách phòng", icon: "📋" },
    { word: "Cleaning record", phonetic: "/ˈkliːnɪŋ ˈrekɔːd/", definition: "Sổ ghi dọn phòng", icon: "📒" },
    { word: "Minibar list", phonetic: "/ˈmɪnibɑː lɪst/", definition: "Bảng kê minibar", icon: "🍫" },
    { word: "Consumed", phonetic: "/kənˈsjuːmd/", definition: "Đã sử dụng", icon: "🍹" },
    { word: "Post the charge", phonetic: "/pəʊst ðə tʃɑːdʒ/", definition: "Ghi phí vào phòng", icon: "💸" },
    { word: "Maintenance form", phonetic: "/ˈmeɪntənəns fɔːm/", definition: "Phiếu báo sửa chữa", icon: "🔧" },
    { word: "Lost property", phonetic: "/lɒst ˈprɒpəti/", definition: "Đồ khách bỏ quên", icon: "🎒" },
    { word: "Hand in", phonetic: "/hænd ɪn/", definition: "Nộp lại", icon: "🤲" },
    { word: "Record the time", phonetic: "/rɪˈkɔːd ðə taɪm/", definition: "Ghi lại giờ", icon: "🕓" },
    { word: "Sign the sheet", phonetic: "/saɪn ðə ʃiːt/", definition: "Ký vào bảng", icon: "✍️" },
  ],
  rules: [
    { word: "Chemical", phonetic: "/ˈkemɪkl/", definition: "Hóa chất tẩy rửa", icon: "🧪" },
    { word: "Gloves", phonetic: "/ɡlʌvz/", definition: "Găng tay", icon: "🧤" },
    { word: "Wet floor sign", phonetic: "/wet flɔː saɪn/", definition: "Biển báo sàn ướt", icon: "⚠️" },
    { word: "Do not mix", phonetic: "/duː nɒt mɪks/", definition: "Không được pha trộn", icon: "🚫" },
    { word: "Heavy item", phonetic: "/ˈhevi ˈaɪtəm/", definition: "Vật nặng", icon: "🏋️" },
    { word: "Lift safely", phonetic: "/lɪft ˈseɪfli/", definition: "Nâng đúng cách", icon: "💪" },
    { word: "Guest privacy", phonetic: "/ɡest ˈprɪvəsi/", definition: "Riêng tư của khách", icon: "🔐" },
    { word: "Never touch", phonetic: "/ˈnevə tʌtʃ/", definition: "Tuyệt đối không chạm", icon: "✋" },
    { word: "Report at once", phonetic: "/rɪˈpɔːt ət wʌns/", definition: "Báo ngay lập tức", icon: "📢" },
    { word: "Compulsory", phonetic: "/kəmˈpʌlsəri/", definition: "Bắt buộc", icon: "❗" },
  ],
  choices: [
    { word: "Cleaning time slot", phonetic: "/ˈkliːnɪŋ taɪm slɒt/", definition: "Khung giờ dọn phòng", icon: "🕐" },
    { word: "Fresh sheets", phonetic: "/freʃ ʃiːts/", definition: "Ga giường mới", icon: "🛏️" },
    { word: "Reused towels", phonetic: "/riːˈjuːzd ˈtaʊəlz/", definition: "Khăn dùng lại", icon: "♻️" },
    { word: "Feather pillow", phonetic: "/ˈfeðə ˈpɪləʊ/", definition: "Gối lông vũ", icon: "🪶" },
    { word: "Foam pillow", phonetic: "/fəʊm ˈpɪləʊ/", definition: "Gối cao su non", icon: "🛌" },
    { word: "Extra blankets", phonetic: "/ˈekstrə ˈblæŋkɪts/", definition: "Chăn bổ sung", icon: "🧣" },
    { word: "Guest preference", phonetic: "/ɡest ˈprefrəns/", definition: "Sở thích của khách", icon: "❓" },
    { word: "Environment", phonetic: "/ɪnˈvaɪrənmənt/", definition: "Môi trường", icon: "🌍" },
    { word: "Water saving", phonetic: "/ˈwɔːtə ˈseɪvɪŋ/", definition: "Việc tiết kiệm nước", icon: "💧" },
    { word: "Guest decision", phonetic: "/ɡest dɪˈsɪʒn/", definition: "Quyết định của khách", icon: "🤲" },
  ],
  reports: [
    { word: "Cleaned", phonetic: "/kliːnd/", definition: "Đã dọn", icon: "✨" },
    { word: "Finished", phonetic: "/ˈfɪnɪʃt/", definition: "Đã hoàn thành", icon: "🏁" },
    { word: "Found", phonetic: "/faʊnd/", definition: "Đã tìm thấy", icon: "🔍" },
    { word: "Reported", phonetic: "/rɪˈpɔːtɪd/", definition: "Đã báo cáo", icon: "📢" },
    { word: "This morning", phonetic: "/ðɪs ˈmɔːnɪŋ/", definition: "Sáng nay", icon: "🌅" },
    { word: "Rooms done", phonetic: "/ruːmz dʌn/", definition: "Số phòng đã xong", icon: "🔢" },
    { word: "Took longer", phonetic: "/tʊk ˈlɒŋɡə/", definition: "Mất nhiều thời gian hơn", icon: "⏳" },
    { word: "Replaced", phonetic: "/rɪˈpleɪst/", definition: "Đã thay mới", icon: "🔄" },
    { word: "Checked out", phonetic: "/tʃekt aʊt/", definition: "Khách đã trả phòng", icon: "📤" },
    { word: "Left behind", phonetic: "/left bɪˈhaɪnd/", definition: "Bỏ quên lại", icon: "🎒" },
  ],
  wrapUp: [
    { word: "All rooms ready", phonetic: "/ɔːl ruːmz ˈredi/", definition: "Toàn bộ phòng sẵn sàng", icon: "✅" },
    { word: "Inspection", phonetic: "/ɪnˈspekʃn/", definition: "Đợt kiểm tra", icon: "🔎" },
    { word: "Supplies", phonetic: "/səˈplaɪz/", definition: "Vật tư tiêu hao", icon: "📦" },
    { word: "Restocked", phonetic: "/ˌriːˈstɒkt/", definition: "Đã bổ sung", icon: "🧴" },
    { word: "Handed over", phonetic: "/ˈhændɪd ˈəʊvə/", definition: "Đã bàn giao", icon: "🤝" },
    { word: "No complaints", phonetic: "/nəʊ kəmˈpleɪnts/", definition: "Không có phàn nàn", icon: "😊" },
    { word: "Trolley clean", phonetic: "/ˈtrɒli kliːn/", definition: "Xe đẩy đã sạch", icon: "🛒" },
    { word: "Ready for tomorrow", phonetic: "/ˈredi fə təˈmɒrəʊ/", definition: "Sẵn sàng cho ngày mai", icon: "📅" },
    { word: "Room count", phonetic: "/ruːm kaʊnt/", definition: "Số phòng đã làm", icon: "🔢" },
    { word: "Well organised", phonetic: "/wel ˈɔːɡənaɪzd/", definition: "Được sắp xếp gọn gàng", icon: "📐" },
  ],
};

const SW_BANK: P2Bank = {
  steps: [
    { word: "Greet at the door", phonetic: "/ɡriːt ət ðə dɔː/", definition: "Đón tại cửa", icon: "🙏" },
    { word: "Check the health form", phonetic: "/tʃek ðə helθ fɔːm/", definition: "Xem phiếu khai sức khỏe", icon: "📋" },
    { word: "Show the locker", phonetic: "/ʃəʊ ðə ˈlɒkə/", definition: "Chỉ tủ đồ", icon: "🔒" },
    { word: "Prepare the foot bath", phonetic: "/prɪˈpeə ðə fʊt bɑːθ/", definition: "Chuẩn bị ngâm chân", icon: "🦶" },
    { word: "Start the treatment", phonetic: "/stɑːt ðə ˈtriːtmənt/", definition: "Bắt đầu liệu trình", icon: "▶️" },
    { word: "Check the comfort", phonetic: "/tʃek ðə ˈkʌmfət/", definition: "Hỏi thăm độ dễ chịu", icon: "❓" },
    { word: "Serve tea after", phonetic: "/sɜːv tiː ˈɑːftə/", definition: "Mời trà sau liệu trình", icon: "🍵" },
    { word: "Walk the guest out", phonetic: "/wɔːk ðə ɡest aʊt/", definition: "Tiễn khách ra", icon: "🚶" },
    { word: "Routine", phonetic: "/ruːˈtiːn/", definition: "Quy trình quen thuộc", icon: "🔁" },
    { word: "Preparation", phonetic: "/ˌprepəˈreɪʃn/", definition: "Sự chuẩn bị", icon: "⏰" },
  ],
  offers: [
    { word: "Body scrub", phonetic: "/ˈbɒdi skrʌb/", definition: "Tẩy tế bào chết", icon: "🧴" },
    { word: "Facial", phonetic: "/ˈfeɪʃl/", definition: "Chăm sóc da mặt", icon: "💆" },
    { word: "Hot towel", phonetic: "/hɒt ˈtaʊəl/", definition: "Khăn nóng", icon: "♨️" },
    { word: "Aroma oil", phonetic: "/əˈrəʊmə ɔɪl/", definition: "Tinh dầu thơm", icon: "🫗" },
    { word: "Extra thirty minutes", phonetic: "/ˈekstrə ˈθɜːti ˈmɪnɪts/", definition: "Thêm ba mươi phút", icon: "⏱️" },
    { word: "Couple room", phonetic: "/ˈkʌpl ruːm/", definition: "Phòng đôi", icon: "💑" },
    { word: "Day pass", phonetic: "/deɪ pɑːs/", definition: "Vé sử dụng trong ngày", icon: "🎫" },
    { word: "Fitness class", phonetic: "/ˈfɪtnəs klɑːs/", definition: "Lớp tập thể dục", icon: "🏋️" },
    { word: "Add on", phonetic: "/æd ɒn/", definition: "Thêm dịch vụ", icon: "➕" },
    { word: "Enhance", phonetic: "/ɪnˈhɑːns/", definition: "Nâng cao trải nghiệm", icon: "⬆️" },
  ],
  details: [
    { word: "Health condition", phonetic: "/helθ kənˈdɪʃn/", definition: "Tình trạng sức khỏe", icon: "❤️" },
    { word: "Pregnancy", phonetic: "/ˈpreɡnənsi/", definition: "Thai kỳ", icon: "🤰" },
    { word: "Injury", phonetic: "/ˈɪndʒəri/", definition: "Chấn thương", icon: "🩹" },
    { word: "Back pain", phonetic: "/bæk peɪn/", definition: "Đau lưng", icon: "😣" },
    { word: "Sensitive skin", phonetic: "/ˈsensətɪv skɪn/", definition: "Da nhạy cảm", icon: "🌸" },
    { word: "Medicine list", phonetic: "/ˈmedsn lɪst/", definition: "Danh sách thuốc đang dùng", icon: "💊" },
    { word: "Focus area", phonetic: "/ˈfəʊkəs ˈeəriə/", definition: "Vùng cần tập trung", icon: "🎯" },
    { word: "Comfortable level", phonetic: "/ˈkʌmftəbl ˈlevl/", definition: "Mức độ dễ chịu", icon: "📊" },
    { word: "Treatment note", phonetic: "/ˈtriːtmənt nəʊt/", definition: "Ghi chú liệu trình", icon: "🔁" },
    { word: "Therapist choice", phonetic: "/ˈθerəpɪst tʃɔɪs/", definition: "Lựa chọn kỹ thuật viên", icon: "✅" },
  ],
  paperwork: [
    { word: "Consent form", phonetic: "/kənˈsent fɔːm/", definition: "Phiếu đồng ý", icon: "📝" },
    { word: "Treatment record", phonetic: "/ˈtriːtmənt ˈrekɔːd/", definition: "Hồ sơ liệu trình", icon: "📒" },
    { word: "Booking sheet", phonetic: "/ˈbʊkɪŋ ʃiːt/", definition: "Bảng lịch hẹn", icon: "🗓️" },
    { word: "Therapist name", phonetic: "/ˈθerəpɪst neɪm/", definition: "Tên kỹ thuật viên", icon: "🧑" },
    { word: "Duration", phonetic: "/djuˈreɪʃn/", definition: "Thời lượng", icon: "⏳" },
    { word: "Total price", phonetic: "/ˈtəʊtl praɪs/", definition: "Tổng giá", icon: "💰" },
    { word: "Room charge", phonetic: "/ruːm tʃɑːdʒ/", definition: "Tính vào phòng", icon: "🏨" },
    { word: "Cancellation", phonetic: "/ˌkænsəˈleɪʃn/", definition: "Việc hủy hẹn", icon: "🚫" },
    { word: "Two hours before", phonetic: "/tuː ˈaʊəz bɪˈfɔː/", definition: "Trước hai tiếng", icon: "🕑" },
    { word: "Fill in", phonetic: "/fɪl ɪn/", definition: "Điền vào", icon: "✏️" },
  ],
  rules: [
    { word: "Shower first", phonetic: "/ˈʃaʊə fɜːst/", definition: "Tắm trước khi vào", icon: "🚿" },
    { word: "No glass", phonetic: "/nəʊ ɡlɑːs/", definition: "Không mang đồ thủy tinh", icon: "🚫" },
    { word: "No diving", phonetic: "/nəʊ ˈdaɪvɪŋ/", definition: "Không nhảy cắm đầu", icon: "🏊" },
    { word: "Silence please", phonetic: "/ˈsaɪləns pliːz/", definition: "Xin giữ im lặng", icon: "🤫" },
    { word: "Mobile phone off", phonetic: "/ˈməʊbaɪl fəʊn ɒf/", definition: "Tắt điện thoại", icon: "📵" },
    { word: "Age limit", phonetic: "/eɪdʒ ˈlɪmɪt/", definition: "Giới hạn độ tuổi", icon: "🔞" },
    { word: "Hot surface", phonetic: "/hɒt ˈsɜːfɪs/", definition: "Bề mặt nóng", icon: "♨️" },
    { word: "Time limit", phonetic: "/taɪm ˈlɪmɪt/", definition: "Giới hạn thời gian", icon: "⏲️" },
    { word: "For your safety", phonetic: "/fə jɔː ˈseɪfti/", definition: "Vì sự an toàn của quý khách", icon: "🛡️" },
    { word: "Must not", phonetic: "/mʌst nɒt/", definition: "Không được phép", icon: "⛔" },
  ],
  choices: [
    { word: "Light or strong", phonetic: "/laɪt ɔː strɒŋ/", definition: "Nhẹ hay mạnh", icon: "💪" },
    { word: "Sixty or ninety", phonetic: "/ˈsɪksti ɔː ˈnaɪnti/", definition: "Sáu mươi hay chín mươi phút", icon: "⏱️" },
    { word: "Lavender", phonetic: "/ˈlævəndə/", definition: "Hương oải hương", icon: "💜" },
    { word: "Lemongrass", phonetic: "/ˈlemənɡrɑːs/", definition: "Hương sả", icon: "🌿" },
    { word: "Morning or evening", phonetic: "/ˈmɔːnɪŋ ɔː ˈiːvnɪŋ/", definition: "Buổi sáng hay buổi tối", icon: "🌅" },
    { word: "Indoor pool", phonetic: "/ˈɪndɔː puːl/", definition: "Hồ bơi trong nhà", icon: "🏊" },
    { word: "First time", phonetic: "/fɜːst taɪm/", definition: "Lần đầu", icon: "🆕" },
    { word: "Popular choice", phonetic: "/ˈpɒpjələ tʃɔɪs/", definition: "Lựa chọn phổ biến", icon: "📊" },
    { word: "Skin type", phonetic: "/skɪn taɪp/", definition: "Loại da", icon: "⚖️" },
    { word: "Therapist advice", phonetic: "/ˈθerəpɪst ədˈvaɪs/", definition: "Lời khuyên kỹ thuật viên", icon: "💡" },
  ],
  reports: [
    { word: "Completed", phonetic: "/kəmˈpliːtɪd/", definition: "Đã hoàn thành", icon: "✅" },
    { word: "Booked", phonetic: "/bʊkt/", definition: "Đã đặt lịch", icon: "📔" },
    { word: "Cancelled", phonetic: "/ˈkænsld/", definition: "Đã hủy", icon: "🚫" },
    { word: "Rescheduled", phonetic: "/ˌriːˈʃedjuːld/", definition: "Đã dời lịch", icon: "🔄" },
    { word: "Last week", phonetic: "/lɑːst wiːk/", definition: "Tuần trước", icon: "📅" },
    { word: "Treatments today", phonetic: "/ˈtriːtmənts təˈdeɪ/", definition: "Số liệu trình hôm nay", icon: "🔢" },
    { word: "Felt better", phonetic: "/felt ˈbetə/", definition: "Cảm thấy khá hơn", icon: "😌" },
    { word: "Cleaned the pool", phonetic: "/kliːnd ðə puːl/", definition: "Đã vệ sinh hồ", icon: "🏊" },
    { word: "Checked the water", phonetic: "/tʃekt ðə ˈwɔːtə/", definition: "Đã kiểm tra nước", icon: "💧" },
    { word: "No incident", phonetic: "/nəʊ ˈɪnsɪdənt/", definition: "Không có sự cố", icon: "👍" },
  ],
  wrapUp: [
    { word: "Fully booked day", phonetic: "/ˈfʊli bʊkt deɪ/", definition: "Ngày kín lịch", icon: "🈵" },
    { word: "Guest returned", phonetic: "/ɡest rɪˈtɜːnd/", definition: "Khách quay lại", icon: "🔁" },
    { word: "Linen washed", phonetic: "/ˈlɪnɪn wɒʃt/", definition: "Đồ vải đã giặt", icon: "🧺" },
    { word: "Oil stock", phonetic: "/ɔɪl stɒk/", definition: "Lượng tinh dầu còn", icon: "🫗" },
    { word: "Calm shift", phonetic: "/kɑːm ʃɪft/", definition: "Ca làm êm ả", icon: "🧘" },
    { word: "Thanked us", phonetic: "/θæŋkt ʌs/", definition: "Đã cảm ơn chúng tôi", icon: "🙏" },
    { word: "Prepared for tomorrow", phonetic: "/prɪˈpeəd fə təˈmɒrəʊ/", definition: "Đã chuẩn bị cho mai", icon: "📅" },
    { word: "Well rested", phonetic: "/wel ˈrestɪd/", definition: "Được nghỉ ngơi tốt", icon: "😴" },
    { word: "Peaceful day", phonetic: "/ˈpiːsfl deɪ/", definition: "Ngày yên bình", icon: "🕊️" },
    { word: "Soft music", phonetic: "/sɒft ˈmjuːzɪk/", definition: "Nhạc nhẹ", icon: "🎵" },
  ],
};

const GR_BANK: P2Bank = {
  steps: [
    { word: "Check the arrival list", phonetic: "/tʃek ði əˈraɪvl lɪst/", definition: "Kiểm tra danh sách khách đến", icon: "📋" },
    { word: "Meet at the lobby", phonetic: "/miːt ət ðə ˈlɒbi/", definition: "Đón ở sảnh", icon: "🏨" },
    { word: "Introduce the club", phonetic: "/ˌɪntrəˈdjuːs ðə klʌb/", definition: "Giới thiệu phòng chờ", icon: "🛋️" },
    { word: "Escort upstairs", phonetic: "/ɪˈskɔːt ˌʌpˈsteəz/", definition: "Dẫn lên tầng trên", icon: "🛗" },
    { word: "Serve refreshment", phonetic: "/sɜːv rɪˈfreʃmənt/", definition: "Mời nước", icon: "🥤" },
    { word: "Note the preference", phonetic: "/nəʊt ðə ˈprefrəns/", definition: "Ghi lại sở thích", icon: "🗒️" },
    { word: "Check again later", phonetic: "/tʃek əˈɡen ˈleɪtə/", definition: "Quay lại hỏi thăm sau", icon: "🔁" },
    { word: "Say goodbye warmly", phonetic: "/seɪ ˌɡʊdˈbaɪ ˈwɔːmli/", definition: "Chào tạm biệt ấm áp", icon: "👋" },
    { word: "Personal touch", phonetic: "/ˈpɜːsənl tʌtʃ/", definition: "Dấu ấn cá nhân", icon: "✨" },
    { word: "Service stage", phonetic: "/ˈsɜːvɪs steɪdʒ/", definition: "Giai đoạn phục vụ", icon: "🪜" },
  ],
  offers: [
    { word: "Late check-out", phonetic: "/leɪt ˈtʃekaʊt/", definition: "Trả phòng muộn", icon: "🕐" },
    { word: "Afternoon tea", phonetic: "/ˌɑːftəˈnuːn tiː/", definition: "Trà chiều", icon: "🍰" },
    { word: "Happy hour", phonetic: "/ˈhæpi ˈaʊə/", definition: "Giờ vàng đồ uống", icon: "🍹" },
    { word: "City tour", phonetic: "/ˈsɪti tʊə/", definition: "Tour tham quan thành phố", icon: "🚌" },
    { word: "Table reservation", phonetic: "/ˈteɪbl ˌrezəˈveɪʃn/", definition: "Đặt bàn giúp khách", icon: "🍽️" },
    { word: "Airport lounge", phonetic: "/ˈeəpɔːt laʊndʒ/", definition: "Phòng chờ sân bay", icon: "✈️" },
    { word: "Room decoration", phonetic: "/ruːm ˌdekəˈreɪʃn/", definition: "Trang trí phòng", icon: "🎊" },
    { word: "Welcome fruit", phonetic: "/ˈwelkəm fruːt/", definition: "Trái cây chào đón", icon: "🍇" },
    { word: "Arrange for you", phonetic: "/əˈreɪndʒ fə juː/", definition: "Sắp xếp giúp quý khách", icon: "🤝" },
    { word: "With pleasure", phonetic: "/wɪð ˈpleʒə/", definition: "Rất hân hạnh", icon: "😊" },
  ],
  details: [
    { word: "Coffee preference", phonetic: "/ˈkɒfi ˈprefrəns/", definition: "Sở thích cà phê", icon: "☕" },
    { word: "Pillow type", phonetic: "/ˈpɪləʊ taɪp/", definition: "Loại gối ưa dùng", icon: "🛌" },
    { word: "Newspaper choice", phonetic: "/ˈnjuːzpeɪpə tʃɔɪs/", definition: "Loại báo ưa đọc", icon: "📰" },
    { word: "Travel purpose", phonetic: "/ˈtrævl ˈpɜːpəs/", definition: "Mục đích chuyến đi", icon: "🎯" },
    { word: "Returning guest", phonetic: "/rɪˈtɜːnɪŋ ɡest/", definition: "Khách quay lại", icon: "🔁" },
    { word: "Children age", phonetic: "/ˈtʃɪldrən eɪdʒ/", definition: "Tuổi các bé", icon: "🧒" },
    { word: "Wake-up time", phonetic: "/ˈweɪk ʌp taɪm/", definition: "Giờ báo thức", icon: "⏰" },
    { word: "Guest note", phonetic: "/ɡest nəʊt/", definition: "Ghi chú về khách", icon: "✅" },
    { word: "Special detail", phonetic: "/ˈspeʃl ˈdiːteɪl/", definition: "Chi tiết đặc biệt", icon: "💭" },
    { word: "Guest file", phonetic: "/ɡest faɪl/", definition: "Hồ sơ khách", icon: "🗂️" },
  ],
  paperwork: [
    { word: "Guest history", phonetic: "/ɡest ˈhɪstri/", definition: "Lịch sử lưu trú", icon: "📚" },
    { word: "Preference sheet", phonetic: "/ˈprefrəns ʃiːt/", definition: "Phiếu ghi sở thích", icon: "📄" },
    { word: "Feedback form", phonetic: "/ˈfiːdbæk fɔːm/", definition: "Phiếu góp ý", icon: "📝" },
    { word: "Club benefit", phonetic: "/klʌb ˈbenɪfɪt/", definition: "Quyền lợi hội viên", icon: "🎁" },
    { word: "Membership number", phonetic: "/ˈmembəʃɪp ˈnʌmbə/", definition: "Số hội viên", icon: "🔢" },
    { word: "Points", phonetic: "/pɔɪnts/", definition: "Điểm tích lũy", icon: "⭐" },
    { word: "Add to the account", phonetic: "/æd tə ði əˈkaʊnt/", definition: "Cộng vào tài khoản", icon: "➕" },
    { word: "Request slip", phonetic: "/rɪˈkwest slɪp/", definition: "Phiếu yêu cầu", icon: "🎫" },
    { word: "Pass to the team", phonetic: "/pɑːs tə ðə tiːm/", definition: "Chuyển cho bộ phận", icon: "➡️" },
    { word: "Update the record", phonetic: "/ʌpˈdeɪt ðə ˈrekɔːd/", definition: "Cập nhật hồ sơ", icon: "🔄" },
  ],
  rules: [
    { word: "Lounge access", phonetic: "/laʊndʒ ˈækses/", definition: "Quyền vào phòng chờ", icon: "🔑" },
    { word: "Two guests only", phonetic: "/tuː ɡests ˈəʊnli/", definition: "Chỉ hai khách", icon: "👥" },
    { word: "Children policy", phonetic: "/ˈtʃɪldrən ˈpɒləsi/", definition: "Quy định trẻ em", icon: "🧒" },
    { word: "Photo permission", phonetic: "/ˈfəʊtəʊ pəˈmɪʃn/", definition: "Xin phép chụp ảnh", icon: "📷" },
    { word: "Private information", phonetic: "/ˈpraɪvət ˌɪnfəˈmeɪʃn/", definition: "Thông tin riêng tư", icon: "🔐" },
    { word: "Do not share", phonetic: "/duː nɒt ʃeə/", definition: "Không được tiết lộ", icon: "🤐" },
    { word: "Dress smart", phonetic: "/dres smɑːt/", definition: "Trang phục lịch sự", icon: "👔" },
    { word: "Closing time", phonetic: "/ˈkləʊzɪŋ taɪm/", definition: "Giờ đóng cửa", icon: "🕙" },
    { word: "Kindly note", phonetic: "/ˈkaɪndli nəʊt/", definition: "Kính mong quý khách lưu ý", icon: "📌" },
    { word: "House rule", phonetic: "/haʊs ruːl/", definition: "Nội quy khách sạn", icon: "📜" },
  ],
  choices: [
    { word: "Lounge or room", phonetic: "/laʊndʒ ɔː ruːm/", definition: "Ở phòng chờ hay tại phòng", icon: "🛋️" },
    { word: "Early or late", phonetic: "/ˈɜːli ɔː leɪt/", definition: "Sớm hay muộn", icon: "🕐" },
    { word: "Private car", phonetic: "/ˈpraɪvət kɑː/", definition: "Xe riêng", icon: "🚗" },
    { word: "Group tour", phonetic: "/ɡruːp tʊə/", definition: "Tour đoàn", icon: "🚌" },
    { word: "Quiet table", phonetic: "/ˈkwaɪət ˈteɪbl/", definition: "Bàn yên tĩnh", icon: "🤫" },
    { word: "Window table", phonetic: "/ˈwɪndəʊ ˈteɪbl/", definition: "Bàn cạnh cửa sổ", icon: "🪟" },
    { word: "Something local", phonetic: "/ˈsʌmθɪŋ ˈləʊkl/", definition: "Món/nơi đặc trưng địa phương", icon: "🏮" },
    { word: "Relaxing option", phonetic: "/rɪˈlæksɪŋ ˈɒpʃn/", definition: "Phương án thư giãn hơn", icon: "😌" },
    { word: "Better plan", phonetic: "/ˈbetə plæn/", definition: "Phương án hợp hơn", icon: "❓" },
    { word: "Perfect match", phonetic: "/ˈpɜːfɪkt mætʃ/", definition: "Lựa chọn hoàn hảo", icon: "🎯" },
  ],
  reports: [
    { word: "Welcomed", phonetic: "/ˈwelkəmd/", definition: "Đã đón tiếp", icon: "🙏" },
    { word: "Arranged", phonetic: "/əˈreɪndʒd/", definition: "Đã sắp xếp", icon: "🗂️" },
    { word: "Delivered", phonetic: "/dɪˈlɪvəd/", definition: "Đã chuyển tới", icon: "📦" },
    { word: "Upgraded", phonetic: "/ˌʌpˈɡreɪdɪd/", definition: "Đã nâng hạng", icon: "⬆️" },
    { word: "This week", phonetic: "/ðɪs wiːk/", definition: "Tuần này", icon: "📅" },
    { word: "VIP arrivals", phonetic: "/ˌviː aɪ ˈpiː əˈraɪvlz/", definition: "Số khách VIP đến", icon: "🌟" },
    { word: "Wrote a note", phonetic: "/rəʊt ə nəʊt/", definition: "Đã viết thiệp", icon: "✉️" },
    { word: "Remembered", phonetic: "/rɪˈmembəd/", definition: "Đã nhớ được", icon: "🧠" },
    { word: "Very pleased", phonetic: "/ˈveri pliːzd/", definition: "Rất hài lòng", icon: "😊" },
    { word: "Passed the message", phonetic: "/pɑːst ðə ˈmesɪdʒ/", definition: "Đã chuyển lời nhắn", icon: "➡️" },
  ],
  wrapUp: [
    { word: "Loyal guest", phonetic: "/ˈlɔɪəl ɡest/", definition: "Khách trung thành", icon: "💛" },
    { word: "Good review", phonetic: "/ɡʊd rɪˈvjuː/", definition: "Đánh giá tốt", icon: "⭐" },
    { word: "Special moment", phonetic: "/ˈspeʃl ˈməʊmənt/", definition: "Khoảnh khắc đặc biệt", icon: "✨" },
    { word: "Small detail", phonetic: "/smɔːl ˈdiːteɪl/", definition: "Chi tiết nhỏ", icon: "🔍" },
    { word: "Made the difference", phonetic: "/meɪd ðə ˈdɪfrəns/", definition: "Tạo nên khác biệt", icon: "🌟" },
    { word: "Thoughtful", phonetic: "/ˈθɔːtfl/", definition: "Chu đáo", icon: "💭" },
    { word: "Next arrival", phonetic: "/nekst əˈraɪvl/", definition: "Lượt khách kế tiếp", icon: "🔜" },
    { word: "Team briefing", phonetic: "/tiːm ˈbriːfɪŋ/", definition: "Họp giao ban", icon: "👥" },
    { word: "Warm welcome", phonetic: "/wɔːm ˈwelkəm/", definition: "Sự đón tiếp nồng hậu", icon: "🤗" },
    { word: "Guest delighted", phonetic: "/ɡest dɪˈlaɪtɪd/", definition: "Khách rất vui", icon: "😍" },
  ],
};

const BO_BANK: P2Bank = {
  steps: [
    { word: "Receive the request", phonetic: "/rɪˈsiːv ðə rɪˈkwest/", definition: "Nhận yêu cầu", icon: "📥" },
    { word: "Check the stock", phonetic: "/tʃek ðə stɒk/", definition: "Kiểm tra tồn kho", icon: "📦" },
    { word: "Prepare the quote", phonetic: "/prɪˈpeə ðə kwəʊt/", definition: "Lập báo giá", icon: "📊" },
    { word: "Get approval", phonetic: "/ɡet əˈpruːvl/", definition: "Xin phê duyệt", icon: "✅" },
    { word: "Place the order", phonetic: "/pleɪs ði ˈɔːdə/", definition: "Đặt hàng", icon: "🛒" },
    { word: "Track the delivery", phonetic: "/træk ðə dɪˈlɪvəri/", definition: "Theo dõi giao hàng", icon: "🚚" },
    { word: "Check the invoice", phonetic: "/tʃek ði ˈɪnvɔɪs/", definition: "Đối chiếu hóa đơn", icon: "🧾" },
    { word: "File the document", phonetic: "/faɪl ðə ˈdɒkjumənt/", definition: "Lưu chứng từ", icon: "🗄️" },
    { word: "Procedure", phonetic: "/prəˈsiːdʒə/", definition: "Quy trình", icon: "📋" },
    { word: "Work stage", phonetic: "/wɜːk steɪdʒ/", definition: "Khâu công việc", icon: "🪜" },
  ],
  offers: [
    { word: "Meeting package", phonetic: "/ˈmiːtɪŋ ˈpækɪdʒ/", definition: "Gói hội nghị", icon: "📦" },
    { word: "Half day rate", phonetic: "/hɑːf deɪ reɪt/", definition: "Giá nửa ngày", icon: "🕐" },
    { word: "Coffee break", phonetic: "/ˈkɒfi breɪk/", definition: "Giải lao cà phê", icon: "☕" },
    { word: "Projector", phonetic: "/prəˈdʒektə/", definition: "Máy chiếu", icon: "📽️" },
    { word: "Microphone", phonetic: "/ˈmaɪkrəfəʊn/", definition: "Micro", icon: "🎤" },
    { word: "Free parking", phonetic: "/friː ˈpɑːkɪŋ/", definition: "Đỗ xe miễn phí", icon: "🅿️" },
    { word: "Extra chairs", phonetic: "/ˈekstrə tʃeəz/", definition: "Ghế bổ sung", icon: "🪑" },
    { word: "Flip chart", phonetic: "/flɪp tʃɑːt/", definition: "Bảng giấy lật", icon: "📊" },
    { word: "At a special rate", phonetic: "/ət ə ˈspeʃl reɪt/", definition: "Với giá ưu đãi", icon: "🏷️" },
    { word: "We can provide", phonetic: "/wiː kən prəˈvaɪd/", definition: "Chúng tôi có thể cung cấp", icon: "🤝" },
  ],
  details: [
    { word: "Event date", phonetic: "/ɪˈvent deɪt/", definition: "Ngày tổ chức", icon: "📅" },
    { word: "Number of people", phonetic: "/ˈnʌmbə əv ˈpiːpl/", definition: "Số người dự", icon: "👥" },
    { word: "Start and end time", phonetic: "/stɑːt ənd end taɪm/", definition: "Giờ bắt đầu và kết thúc", icon: "🕓" },
    { word: "Contact person", phonetic: "/ˈkɒntækt ˈpɜːsn/", definition: "Người liên hệ", icon: "🧑‍💼" },
    { word: "Billing details", phonetic: "/ˈbɪlɪŋ ˈdiːteɪlz/", definition: "Thông tin xuất hóa đơn", icon: "🧾" },
    { word: "Room layout", phonetic: "/ruːm ˈleɪaʊt/", definition: "Cách bố trí phòng", icon: "🪑" },
    { word: "Change request", phonetic: "/tʃeɪndʒ rɪˈkwest/", definition: "Yêu cầu thay đổi", icon: "🔄" },
    { word: "Meeting note", phonetic: "/ˈmiːtɪŋ nəʊt/", definition: "Biên bản họp", icon: "🔁" },
    { word: "Written confirmation", phonetic: "/ˈrɪtn ˌkɒnfəˈmeɪʃn/", definition: "Xác nhận bằng văn bản", icon: "📄" },
    { word: "Email reply", phonetic: "/ˈiːmeɪl rɪˈplaɪ/", definition: "Thư trả lời", icon: "📧" },
  ],
  paperwork: [
    { word: "Purchase order", phonetic: "/ˈpɜːtʃəs ˈɔːdə/", definition: "Đơn đặt mua", icon: "📝" },
    { word: "Delivery note", phonetic: "/dɪˈlɪvəri nəʊt/", definition: "Phiếu giao hàng", icon: "🚚" },
    { word: "Receipt copy", phonetic: "/rɪˈsiːt ˈkɒpi/", definition: "Bản sao biên lai", icon: "🧾" },
    { word: "Payment term", phonetic: "/ˈpeɪmənt tɜːm/", definition: "Điều khoản thanh toán", icon: "📆" },
    { word: "Thirty days", phonetic: "/ˈθɜːti deɪz/", definition: "Ba mươi ngày", icon: "📅" },
    { word: "Bank transfer", phonetic: "/bæŋk ˈtrænsfɜː/", definition: "Chuyển khoản ngân hàng", icon: "🏦" },
    { word: "Stamp", phonetic: "/stæmp/", definition: "Con dấu", icon: "🔖" },
    { word: "Attach", phonetic: "/əˈtætʃ/", definition: "Đính kèm", icon: "📎" },
    { word: "Approve", phonetic: "/əˈpruːv/", definition: "Phê duyệt", icon: "✅" },
    { word: "Reference number", phonetic: "/ˈrefrəns ˈnʌmbə/", definition: "Số tham chiếu", icon: "🔢" },
  ],
  rules: [
    { word: "Staff entrance only", phonetic: "/stɑːf ˈentrəns ˈəʊnli/", definition: "Chỉ dành cho nhân viên", icon: "🚪" },
    { word: "Wear the badge", phonetic: "/weə ðə bædʒ/", definition: "Đeo thẻ nhân viên", icon: "🏷️" },
    { word: "Clock in", phonetic: "/klɒk ɪn/", definition: "Chấm công vào ca", icon: "⏱️" },
    { word: "Confidential file", phonetic: "/ˌkɒnfɪˈdenʃl faɪl/", definition: "Hồ sơ mật", icon: "🔐" },
    { word: "Password", phonetic: "/ˈpɑːswɜːd/", definition: "Mật khẩu", icon: "🔑" },
    { word: "Lock the office", phonetic: "/lɒk ði ˈɒfɪs/", definition: "Khóa văn phòng", icon: "🔒" },
    { word: "No personal use", phonetic: "/nəʊ ˈpɜːsənl juːs/", definition: "Không dùng việc riêng", icon: "🚫" },
    { word: "Company policy", phonetic: "/ˈkʌmpəni ˈpɒləsi/", definition: "Chính sách công ty", icon: "📜" },
    { word: "Health and safety", phonetic: "/helθ ənd ˈseɪfti/", definition: "An toàn lao động", icon: "🦺" },
    { word: "Required", phonetic: "/rɪˈkwaɪəd/", definition: "Bắt buộc", icon: "❗" },
  ],
  choices: [
    { word: "Supplier A or B", phonetic: "/səˈplaɪə eɪ ɔː biː/", definition: "Nhà cung cấp A hay B", icon: "🏭" },
    { word: "Cheaper option", phonetic: "/ˈtʃiːpə ˈɒpʃn/", definition: "Phương án rẻ hơn", icon: "🪙" },
    { word: "Better quality", phonetic: "/ˈbetə ˈkwɒləti/", definition: "Chất lượng tốt hơn", icon: "💎" },
    { word: "Faster delivery", phonetic: "/ˈfɑːstə dɪˈlɪvəri/", definition: "Giao nhanh hơn", icon: "⚡" },
    { word: "Long term", phonetic: "/lɒŋ tɜːm/", definition: "Dài hạn", icon: "📈" },
    { word: "Trial order", phonetic: "/ˈtraɪəl ˈɔːdə/", definition: "Đơn hàng dùng thử", icon: "🧪" },
    { word: "Comparison", phonetic: "/kəmˈpærɪsn/", definition: "Sự so sánh", icon: "⚖️" },
    { word: "Value for money", phonetic: "/ˈvæljuː fə ˈmʌni/", definition: "Đáng đồng tiền", icon: "💰" },
    { word: "Personal opinion", phonetic: "/ˈpɜːsənl əˈpɪnjən/", definition: "Ý kiến cá nhân", icon: "💭" },
    { word: "Final decision", phonetic: "/ˈfaɪnl dɪˈsɪʒn/", definition: "Quyết định cuối cùng", icon: "❓" },
  ],
  reports: [
    { word: "Sent", phonetic: "/sent/", definition: "Đã gửi", icon: "📤" },
    { word: "Received", phonetic: "/rɪˈsiːvd/", definition: "Đã nhận", icon: "📥" },
    { word: "Paid", phonetic: "/peɪd/", definition: "Đã thanh toán", icon: "💳" },
    { word: "Signed", phonetic: "/saɪnd/", definition: "Đã ký", icon: "✍️" },
    { word: "Last month", phonetic: "/lɑːst mʌnθ/", definition: "Tháng trước", icon: "📅" },
    { word: "Delivered late", phonetic: "/dɪˈlɪvəd leɪt/", definition: "Giao trễ hạn", icon: "⏰" },
    { word: "Checked the figures", phonetic: "/tʃekt ðə ˈfɪɡəz/", definition: "Đã kiểm tra số liệu", icon: "🔢" },
    { word: "Followed up", phonetic: "/ˈfɒləʊd ʌp/", definition: "Đã theo dõi tiếp", icon: "🔍" },
    { word: "Agreed", phonetic: "/əˈɡriːd/", definition: "Đã thống nhất", icon: "🤝" },
    { word: "Reported to", phonetic: "/rɪˈpɔːtɪd tuː/", definition: "Đã báo cáo lên", icon: "📢" },
  ],
  wrapUp: [
    { word: "On budget", phonetic: "/ɒn ˈbʌdʒɪt/", definition: "Đúng ngân sách", icon: "💰" },
    { word: "Target", phonetic: "/ˈtɑːɡɪt/", definition: "Chỉ tiêu", icon: "🎯" },
    { word: "Monthly report", phonetic: "/ˈmʌnθli rɪˈpɔːt/", definition: "Báo cáo tháng", icon: "📄" },
    { word: "Saved cost", phonetic: "/seɪvd kɒst/", definition: "Đã tiết kiệm chi phí", icon: "📉" },
    { word: "Good result", phonetic: "/ɡʊd rɪˈzʌlt/", definition: "Kết quả tốt", icon: "📈" },
    { word: "Filed properly", phonetic: "/faɪld ˈprɒpəli/", definition: "Đã lưu đúng cách", icon: "🗄️" },
    { word: "Next quarter", phonetic: "/nekst ˈkwɔːtə/", definition: "Quý tới", icon: "📆" },
    { word: "All up to date", phonetic: "/ɔːl ʌp tə deɪt/", definition: "Mọi thứ đã cập nhật", icon: "✅" },
    { word: "Cost control", phonetic: "/kɒst kənˈtrəʊl/", definition: "Kiểm soát chi phí", icon: "📉" },
    { word: "Files closed", phonetic: "/faɪlz kləʊzd/", definition: "Hồ sơ đã đóng", icon: "🗄️" },
  ],
};

export const P2_BANKS: Record<string, P2Bank> = {
  FO: FO_BANK,
  FB: FB_BANK,
  HK: HK_BANK,
  SW: SW_BANK,
  GR: GR_BANK,
  BO: BO_BANK,
};
