/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgAdminRouteImport } from './routes/org-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppraisalRouteImport } from './routes/appraisal'
import { Route as AdminLoungeRouteImport } from './routes/admin-lounge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepartmentDepRouteImport } from './routes/department.$dep'
import { Route as LearnDepWeekSuiteRouteImport } from './routes/learn.$dep.$week.$suite'
import { Route as DepartmentDepWeekWeekRouteImport } from './routes/department_.$dep.week.$week'

const OrgAdminRoute = OrgAdminRouteImport.update({
  id: '/org-admin',
  path: '/org-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalRoute = AppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoungeRoute = AdminLoungeRouteImport.update({
  id: '/admin-lounge',
  path: '/admin-lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentDepRoute = DepartmentDepRouteImport.update({
  id: '/department/$dep',
  path: '/department/$dep',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDepWeekSuiteRoute = LearnDepWeekSuiteRouteImport.update({
  id: '/learn/$dep/$week/$suite',
  path: '/learn/$dep/$week/$suite',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentDepWeekWeekRoute = DepartmentDepWeekWeekRouteImport.update({
  id: '/department_/$dep/week/$week',
  path: '/department/$dep/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-lounge': typeof AdminLoungeRoute
  '/appraisal': typeof AppraisalRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/org-admin': typeof OrgAdminRoute
  '/department/$dep': typeof DepartmentDepRoute
  '/department/$dep/week/$week': typeof DepartmentDepWeekWeekRoute
  '/learn/$dep/$week/$suite': typeof LearnDepWeekSuiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-lounge': typeof AdminLoungeRoute
  '/appraisal': typeof AppraisalRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/org-admin': typeof OrgAdminRoute
  '/department/$dep': typeof DepartmentDepRoute
  '/department/$dep/week/$week': typeof DepartmentDepWeekWeekRoute
  '/learn/$dep/$week/$suite': typeof LearnDepWeekSuiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-lounge': typeof AdminLoungeRoute
  '/appraisal': typeof AppraisalRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/org-admin': typeof OrgAdminRoute
  '/department/$dep': typeof DepartmentDepRoute
  '/department_/$dep/week/$week': typeof DepartmentDepWeekWeekRoute
  '/learn/$dep/$week/$suite': typeof LearnDepWeekSuiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-lounge'
    | '/appraisal'
    | '/change-password'
    | '/login'
    | '/org-admin'
    | '/department/$dep'
    | '/department/$dep/week/$week'
    | '/learn/$dep/$week/$suite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-lounge'
    | '/appraisal'
    | '/change-password'
    | '/login'
    | '/org-admin'
    | '/department/$dep'
    | '/department/$dep/week/$week'
    | '/learn/$dep/$week/$suite'
  id:
    | '__root__'
    | '/'
    | '/admin-lounge'
    | '/appraisal'
    | '/change-password'
    | '/login'
    | '/org-admin'
    | '/department/$dep'
    | '/department_/$dep/week/$week'
    | '/learn/$dep/$week/$suite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoungeRoute: typeof AdminLoungeRoute
  AppraisalRoute: typeof AppraisalRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  OrgAdminRoute: typeof OrgAdminRoute
  DepartmentDepRoute: typeof DepartmentDepRoute
  DepartmentDepWeekWeekRoute: typeof DepartmentDepWeekWeekRoute
  LearnDepWeekSuiteRoute: typeof LearnDepWeekSuiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/org-admin': {
      id: '/org-admin'
      path: '/org-admin'
      fullPath: '/org-admin'
      preLoaderRoute: typeof OrgAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisal': {
      id: '/appraisal'
      path: '/appraisal'
      fullPath: '/appraisal'
      preLoaderRoute: typeof AppraisalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lounge': {
      id: '/admin-lounge'
      path: '/admin-lounge'
      fullPath: '/admin-lounge'
      preLoaderRoute: typeof AdminLoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/$dep': {
      id: '/department/$dep'
      path: '/department/$dep'
      fullPath: '/department/$dep'
      preLoaderRoute: typeof DepartmentDepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$dep/$week/$suite': {
      id: '/learn/$dep/$week/$suite'
      path: '/learn/$dep/$week/$suite'
      fullPath: '/learn/$dep/$week/$suite'
      preLoaderRoute: typeof LearnDepWeekSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department_/$dep/week/$week': {
      id: '/department_/$dep/week/$week'
      path: '/department/$dep/week/$week'
      fullPath: '/department/$dep/week/$week'
      preLoaderRoute: typeof DepartmentDepWeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoungeRoute: AdminLoungeRoute,
  AppraisalRoute: AppraisalRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  OrgAdminRoute: OrgAdminRoute,
  DepartmentDepRoute: DepartmentDepRoute,
  DepartmentDepWeekWeekRoute: DepartmentDepWeekWeekRoute,
  LearnDepWeekSuiteRoute: LearnDepWeekSuiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
